<a href="https://colab.research.google.com/github/vcellmike/PatternsFormation/blob/main/Working/2024_08_21_XGBoost_on_ImageJ_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import json
import os
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from sklearn.metrics import accuracy_score, classification_report
from transformers import AutoModel, AutoTokenizer, get_scheduler
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from torch.optim import AdamW
from tqdm.notebook import tqdm, trange
from time import perf_counter
from PIL import Image
import pandas as pd
#from google.colab import drive
from PIL import Image
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import pickle

print("All dependencies present.")

All dependencies present.

In [11]:
# set random seeds for repeatability
import numpy as np
import random

def set_seed(seed_val):
    random.seed(seed_val)
    np.random.seed(seed_val)
    torch.manual_seed(seed_val)
    torch.cuda.manual_seed_all(seed_val)

print("Seed set")

Seed set

In [12]:
seed_val = 42
set_seed(seed_val)

In [13]:
file_in = "data/unclassified_features_39517"

with open(file_in + '.pkl', 'rb') as f:
    feats_df = pickle.load(f)

#load in dataframe
pd.set_option('display.max_columns', None)

file_out = file_in + "_s" + str(seed_val) + "_XGB" + ".model"

print(file_out)
print(feats_df.shape)

feats_df.head()

data/unclassified_features_39517_s42_XGB.model
(39517, 111)

,Ua,Ui,Ga,Gi,Ba,Da,Di,pattern,noise,path,seed,dir,feat_bool,num_spots,Mean,Median,Area_mean,Area_std,X_mean,X_std,Y_mean,Y_std,Perim._mean,Perim._std,BX_mean,BX_std,BY_mean,BY_std,Width_mean,Width_std,Height_mean,Height_std,Major_mean,Major_std,Minor_mean,Minor_std,Angle_mean,Angle_std,Circ._mean,Circ._std,Feret_mean,Feret_std,IntDen_mean,IntDen_std,%Area_mean,%Area_std,RawIntDen_mean,RawIntDen_std,FeretX_mean,FeretX_std,FeretY_mean,FeretY_std,FeretAngle_mean,FeretAngle_std,MinFeret_mean,MinFeret_std,AR_mean,AR_std,Round_mean,Round_std,Solidity_mean,Solidity_std,num_spots_inverted,Mean_inverted,Median_inverted,Area_inverted_mean,Area_inverted_std,X_inverted_mean,X_inverted_std,Y_inverted_mean,Y_inverted_std,Perim._inverted_mean,Perim._inverted_std,BX_inverted_mean,BX_inverted_std,BY_inverted_mean,BY_inverted_std,Width_inverted_mean,Width_inverted_std,Height_inverted_mean,Height_inverted_std,Major_inverted_mean,Major_inverted_std,Minor_inverted_mean,Minor_inverted_std,Angle_inverted_mean,Angle_inverted_std,Circ._inverted_mean,Circ._inverted_std,Feret_inverted_mean,Feret_inverted_std,IntDen_inverted_mean,IntDen_inverted_std,%Area_inverted_mean,%Area_inverted_std,RawIntDen_inverted_mean,RawIntDen_inverted_std,FeretX_inverted_mean,FeretX_inverted_std,FeretY_inverted_mean,FeretY_inverted_std,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std
0,0.011652,0.1066,0.115805,0.061599,-0.043244,0.007928,0.559698,0,2,0.png,0,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.00000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
1,0.025122,0.063822,0.071957,0.106327,-0.113131,0.009186,0.611871,1,2,1.png,1,/content/Images3/,1,70,5.489,0,12.300000,2.548669,99.395943,58.506181,97.530229,58.913237,12.282143,1.400962,97.371429,58.453442,95.528571,58.843551,4.071429,0.723512,4.057143,0.753766,4.245571,0.439294,3.664200,0.511781,55.108900,57.413924,0.958686,0.069883,4.926700,0.412294,3.136500e+03,649.910626,100.0,0.0,3.136500e+03,649.910626,97.942857,58.572760,96.014286,58.843981,120.12900,30.775307,3.653171,0.564778,1.177686,0.183575,0.866686,0.115368,0.879486,0.067138,1,249.511,255,39139.0,0.0,99.998,0.0,100.022,0.0,811.882,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.351,0.0,223.117,0.0,38.796,0.0,0.746,0.0,282.843,0.0,9980445.0,0.0,100.0,0.0,9980445.0,0.0,0.0,0.0,200.0,0.0,45.0,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.979,0.0
2,0.014455,0.085124,0.091124,0.113974,-0.060333,0.001776,1.798215,0,2,2.png,2,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.00000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
3,0.034475,0.059956,0.080798,0.10037,-0.132577,0.008852,0.854084,1,2,3.png,3,/content/Images3/,1,63,4.921,0,12.253968,2.569468,101.800571,59.297600,99.451270,58.953924,11.663270,1.365051,99.968254,59.323693,97.619048,58.964458,3.666667,0.534522,3.666667,0.534522,4.237317,0.401713,3.661714,0.572434,56.049556,60.605082,0.999619,0.003000,4.908365,0.491745,3.124762e+03,655.214389,100.0,0.0,3.124762e+03,655.214389,100.158730,59.330446,98.079365,59.017431,120.19119,32.406426,3.476190,0.613529,1.185032,0.226780,0.867667,0.127976,0.954905,0.046408,1,250.078,255,39228.0,0.0,99.992,0.0,100.015,0.0,809.255,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.524,0.0,223.451,0.0,72.380,0.0,0.753,0.0,282.843,0.0,10003140.0,0.0,100.0,0.0,10003140.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.981,0.0
4,0.025569,0.143322,0.154726,0.025138,-0.067635,0.009413,1.87632,0,2,4.png,4,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.00000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0

In [14]:
print(feats_df.shape)
feats_df.head()

(39517, 111)

,Ua,Ui,Ga,Gi,Ba,Da,Di,pattern,noise,path,seed,dir,feat_bool,num_spots,Mean,Median,Area_mean,Area_std,X_mean,X_std,Y_mean,Y_std,Perim._mean,Perim._std,BX_mean,BX_std,BY_mean,BY_std,Width_mean,Width_std,Height_mean,Height_std,Major_mean,Major_std,Minor_mean,Minor_std,Angle_mean,Angle_std,Circ._mean,Circ._std,Feret_mean,Feret_std,IntDen_mean,IntDen_std,%Area_mean,%Area_std,RawIntDen_mean,RawIntDen_std,FeretX_mean,FeretX_std,FeretY_mean,FeretY_std,FeretAngle_mean,FeretAngle_std,MinFeret_mean,MinFeret_std,AR_mean,AR_std,Round_mean,Round_std,Solidity_mean,Solidity_std,num_spots_inverted,Mean_inverted,Median_inverted,Area_inverted_mean,Area_inverted_std,X_inverted_mean,X_inverted_std,Y_inverted_mean,Y_inverted_std,Perim._inverted_mean,Perim._inverted_std,BX_inverted_mean,BX_inverted_std,BY_inverted_mean,BY_inverted_std,Width_inverted_mean,Width_inverted_std,Height_inverted_mean,Height_inverted_std,Major_inverted_mean,Major_inverted_std,Minor_inverted_mean,Minor_inverted_std,Angle_inverted_mean,Angle_inverted_std,Circ._inverted_mean,Circ._inverted_std,Feret_inverted_mean,Feret_inverted_std,IntDen_inverted_mean,IntDen_inverted_std,%Area_inverted_mean,%Area_inverted_std,RawIntDen_inverted_mean,RawIntDen_inverted_std,FeretX_inverted_mean,FeretX_inverted_std,FeretY_inverted_mean,FeretY_inverted_std,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std
0,0.011652,0.1066,0.115805,0.061599,-0.043244,0.007928,0.559698,0,2,0.png,0,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.00000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
1,0.025122,0.063822,0.071957,0.106327,-0.113131,0.009186,0.611871,1,2,1.png,1,/content/Images3/,1,70,5.489,0,12.300000,2.548669,99.395943,58.506181,97.530229,58.913237,12.282143,1.400962,97.371429,58.453442,95.528571,58.843551,4.071429,0.723512,4.057143,0.753766,4.245571,0.439294,3.664200,0.511781,55.108900,57.413924,0.958686,0.069883,4.926700,0.412294,3.136500e+03,649.910626,100.0,0.0,3.136500e+03,649.910626,97.942857,58.572760,96.014286,58.843981,120.12900,30.775307,3.653171,0.564778,1.177686,0.183575,0.866686,0.115368,0.879486,0.067138,1,249.511,255,39139.0,0.0,99.998,0.0,100.022,0.0,811.882,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.351,0.0,223.117,0.0,38.796,0.0,0.746,0.0,282.843,0.0,9980445.0,0.0,100.0,0.0,9980445.0,0.0,0.0,0.0,200.0,0.0,45.0,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.979,0.0
2,0.014455,0.085124,0.091124,0.113974,-0.060333,0.001776,1.798215,0,2,2.png,2,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.00000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
3,0.034475,0.059956,0.080798,0.10037,-0.132577,0.008852,0.854084,1,2,3.png,3,/content/Images3/,1,63,4.921,0,12.253968,2.569468,101.800571,59.297600,99.451270,58.953924,11.663270,1.365051,99.968254,59.323693,97.619048,58.964458,3.666667,0.534522,3.666667,0.534522,4.237317,0.401713,3.661714,0.572434,56.049556,60.605082,0.999619,0.003000,4.908365,0.491745,3.124762e+03,655.214389,100.0,0.0,3.124762e+03,655.214389,100.158730,59.330446,98.079365,59.017431,120.19119,32.406426,3.476190,0.613529,1.185032,0.226780,0.867667,0.127976,0.954905,0.046408,1,250.078,255,39228.0,0.0,99.992,0.0,100.015,0.0,809.255,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.524,0.0,223.451,0.0,72.380,0.0,0.753,0.0,282.843,0.0,10003140.0,0.0,100.0,0.0,10003140.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.981,0.0
4,0.025569,0.143322,0.154726,0.025138,-0.067635,0.009413,1.87632,0,2,4.png,4,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.00000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0

In [15]:
print(feats_df.columns[13:111])

Index(['num_spots', 'Mean', 'Median', 'Area_mean', 'Area_std', 'X_mean',
       'X_std', 'Y_mean', 'Y_std', 'Perim._mean', 'Perim._std', 'BX_mean',
       'BX_std', 'BY_mean', 'BY_std', 'Width_mean', 'Width_std', 'Height_mean',
       'Height_std', 'Major_mean', 'Major_std', 'Minor_mean', 'Minor_std',
       'Angle_mean', 'Angle_std', 'Circ._mean', 'Circ._std', 'Feret_mean',
       'Feret_std', 'IntDen_mean', 'IntDen_std', '%Area_mean', '%Area_std',
       'RawIntDen_mean', 'RawIntDen_std', 'FeretX_mean', 'FeretX_std',
       'FeretY_mean', 'FeretY_std', 'FeretAngle_mean', 'FeretAngle_std',
       'MinFeret_mean', 'MinFeret_std', 'AR_mean', 'AR_std', 'Round_mean',
       'Round_std', 'Solidity_mean', 'Solidity_std', 'num_spots_inverted',
       'Mean_inverted', 'Median_inverted', 'Area_inverted_mean',
       'Area_inverted_std', 'X_inverted_mean', 'X_inverted_std',
       'Y_inverted_mean', 'Y_inverted_std', 'Perim._inverted_mean',
       'Perim._inverted_std', 'BX_inverted_mean', 'BX_inverted_std',
       'BY_inverted_mean', 'BY_inverted_std', 'Width_inverted_mean',
       'Width_inverted_std', 'Height_inverted_mean', 'Height_inverted_std',
       'Major_inverted_mean', 'Major_inverted_std', 'Minor_inverted_mean',
       'Minor_inverted_std', 'Angle_inverted_mean', 'Angle_inverted_std',
       'Circ._inverted_mean', 'Circ._inverted_std', 'Feret_inverted_mean',
       'Feret_inverted_std', 'IntDen_inverted_mean', 'IntDen_inverted_std',
       '%Area_inverted_mean', '%Area_inverted_std', 'RawIntDen_inverted_mean',
       'RawIntDen_inverted_std', 'FeretX_inverted_mean', 'FeretX_inverted_std',
       'FeretY_inverted_mean', 'FeretY_inverted_std',
       'FeretAngle_inverted_mean', 'FeretAngle_inverted_std',
       'MinFeret_inverted_mean', 'MinFeret_inverted_std', 'AR_inverted_mean',
       'AR_inverted_std', 'Round_inverted_mean', 'Round_inverted_std',
       'Solidity_inverted_mean', 'Solidity_inverted_std'],
      dtype='object')

XGBOOST

In [16]:
#! pip install xgboost
#! pip install openpyxl
#! pip install tensorflow
#! pip install graphviz
#! pip install hyperopt

from sklearn.multioutput import MultiOutputRegressor
from sklearn.svm import SVR
import numpy as np
from sklearn.model_selection import RepeatedKFold
from numpy import absolute
from pandas import read_csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from xgboost import XGBRegressor
import openpyxl
from xgboost import cv
from PIL import Image
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import operator
# for loading/processing the images
import tensorflow
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from keras.applications.vgg16 import preprocess_input

# models
from keras.applications.vgg16 import VGG16
from keras.models import Model

# clustering and dimension reduction
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import pickle
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree
import graphviz
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from hyperopt import fmin, tpe, hp,STATUS_OK
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

print("All dependencies present")

All dependencies present

In [17]:
# scale data 
# uses Standard Scaler, range [-1, 1]

## X (independent variable) --> the feature values themselves
X = feats_df[feats_df.columns[13:111]].astype(float)

## Y (dependent variables) --> the parameter values of Negan and RTO themselves
y = feats_df[["Ua","Ui","Ga","Gi","Da","Di","Ba"]].astype(float)

#Scale data with standardscaler
scaling = StandardScaler()

# Use fit and transform method
scaling.fit(X)
X_scaled = scaling.transform(X)

# select 20 percent for testing
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42) #create training split

In [18]:
print(X_test)
#print(y_train)

[[ 0.84427681 -0.56527056 -0.81564454 ... -0.30076773 -0.9992852
  -0.26485482]
 [ 1.04601638  0.03622808 -0.81564454 ... -0.30076773 -3.22997976
  -0.26485482]
 [-0.46172146  1.28776123  1.22602426 ... -0.30076773  0.56389092
  -0.26485482]
 ...
 [-0.47233933 -0.98652117 -0.81564454 ... -0.30076773  0.56389092
  -0.26485482]
 [-0.47233933 -0.98652117 -0.81564454 ... -0.30076773  0.56389092
  -0.26485482]
 [-0.42986785  0.56368322  1.22602426 ...  3.92583447 -0.52963874
   2.96037405]]

In [19]:
y_test

             Ua        Ui        Ga        Gi        Da        Di        Ba
27444  0.034815  0.086269  0.098214  0.111581  0.010052  1.299758 -0.097848
11068  0.030000  0.240000  0.075000  0.100000  0.013000  0.500000 -0.120000
21463  0.015112  0.146368  0.100549  0.063209  0.010806  0.530263 -0.178364
31013  0.027648  0.159852  0.166757  0.120432  0.011730  1.441355 -0.128601
16157  0.014156  0.136370  0.043016  0.117460  0.008501  0.260931 -0.058947
...         ...       ...       ...       ...       ...       ...       ...
27390  0.050426  0.077152  0.085455  0.127332  0.011023  0.739167 -0.123279
3082   0.050221  0.165615  0.046623  0.175211  0.010444  1.380281 -0.058233
37277  0.034758  0.025755  0.161337  0.160499  0.011274  0.992567 -0.125318
31798  0.046418  0.174132  0.050813  0.173091  0.009446  0.788921 -0.105999
4729   0.039182  0.125528  0.103809  0.069145  0.010173  0.994829 -0.100656

[7904 rows x 7 columns]

In [20]:
model = xgb.XGBRegressor(n_estimators=1000, max_depth=10, eta=0.1, subsample=0.7, colsample_bytree=0.8, num_boost_round=50, objective= "reg:squarederror", device = "cuda")
model.fit(X_train, y_train)

/Users/mikhailblinov/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [14:27:18] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:196: XGBoost is not compiled with CUDA support.
  warnings.warn(smsg, UserWarning)
/Users/mikhailblinov/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [14:27:18] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740:
Parameters: { "num_boost_round" } are not used.

  warnings.warn(smsg, UserWarning)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eta=0.1, eval_metric=None,
             feature_types=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=None, num_boost_round=50, ...)

In [21]:
## Save XGBoost Model to File
model.save_model(file_out)

/Users/mikhailblinov/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [14:27:51] WARNING: /Users/runner/work/xgboost/xgboost/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  warnings.warn(smsg, UserWarning)

In [22]:
loaded_model = xgb.XGBRegressor()

loaded_model.load_model(file_out)

#loaded_model.fit(X_train, y_train)

# make predictions
y_pred = loaded_model.predict(X_test)

pd.DataFrame(data=y_pred) 

# Columns - parameters 1-7
# Rows - Subsample of rows

print("Model loaded")

Model loaded

In [23]:
# GOAL: To determine the error rate in predicting the value of continuous, parameter data

# Converts test Y values to numpy array
true_vals = np.array(y_test)

# Outputs amount of true values
print(true_vals.shape)

# Outputs amount of predicted values
print(y_pred.shape)

# Sets counters for correct, incorrect, errors numpy array
correct = 0
incorrect = 0
p_errs = np.zeros(7)

# loops through each row in the true_vals array
for i in range(true_vals.shape[0]):
  # predicted value = predicted value from loop
  pred = y_pred[i]
  # true value = true value from loop
  true_val = true_vals[i]
  # Adds to error: absolute percent difference between true and predicted values
  p_errs += (np.abs((pred-true_val)/true_val))

# Outputs error percentages
print((p_errs/true_vals.shape[0])*100)

(7904, 7)
(7904, 7)
[146.50361786 120.20670433  87.90838201  72.57677275          inf
  53.51171384  56.57515089]

/var/folders/3p/pbgs38h94vdd8kjwbd33x40h0000gr/T/ipykernel_19280/1689613994.py:24: RuntimeWarning: divide by zero encountered in divide
  p_errs += (np.abs((pred-true_val)/true_val))

In [26]:
# select features of real images

new_df = pd.read_pickle("data/real_df_xgboost.pkl")
new_feats = new_df[new_df.columns[3:111]]

# new_df = pd.read_pickle("./data/Images_Classified_np126.pkl")
# new_feats = new_df[new_df.columns[13:111]]

print(new_feats.head())

y_pred = None

loaded_model = xgb.XGBRegressor()

loaded_model.load_model(file_out)


#scale data
scaling=StandardScaler()

# Use fit and transform method
scaling.fit(new_feats)
new_feats_scaled = scaling.transform(new_feats)
print(new_feats_scaled.shape)

# predict params of images from real feats
y_pred = loaded_model.predict(new_feats_scaled)
print(y_pred[2])

new_df["pred_params"] = list(y_pred)

   num_spots     Mean  Median     Area_mean      Area_std      X_mean  \
0        101    5.699       0      8.851485     11.066304  125.673327
1         49   23.479       0     75.163265    103.827240   99.147755
2          2  251.322     255  19711.500000  19688.500000  148.632000
3         77   15.306       0     31.181818     46.025890  101.898026
4         32   62.124       0    304.531250    876.516507  104.642344

       X_std      Y_mean      Y_std  Perim._mean  Perim._std     BX_mean  \
0  57.972907   88.902515  52.059334    10.451525    8.653331  123.960396
1  55.940428   74.931612  51.325268    36.572388   37.781366   95.387755
2  49.216000   51.684500  49.271500   437.255000  417.941000   97.000000
3  40.868593  104.009818  57.481703    19.575195   18.250837   99.701299
4  49.916328   82.908906  45.964830    98.939469  229.053596   97.843750

      BX_std     BY_mean     BY_std  Width_mean  Width_std  Height_mean  \
0  57.832452   87.297030  52.027705    3.435644   2.619107     3.188119
1  55.720445   68.224490  47.695576    7.571429   6.676184    13.428571
2  97.000000    0.000000   0.000000  103.000000  97.000000   103.000000
3  41.001763  100.246753  57.180315    4.337662   3.451370     7.363636
4  52.672994   69.250000  46.896828   13.187500  23.177896    23.937500

   Height_std  Major_mean   Major_std  Minor_mean   Minor_std  Angle_mean  \
0    2.423944    3.860287    2.502460    2.196881    1.250776   50.320287
1   13.490738   12.331796   11.379018    5.113531    3.973676   73.345184
2   97.000000  115.674500  108.751500  113.879500  109.649500  124.750000
3    7.059872    7.314792    6.449969    3.544974    2.646633   75.761312
4   43.999956   18.785969   27.853125    7.510688   11.242490   71.322094

   Angle_std  Circ._mean  Circ._std  Feret_mean   Feret_std   IntDen_mean  \
0  53.900986    0.857059   0.194583    4.505861    3.106018  2.257129e+03
1  38.726102    0.654939   0.264055   14.381224   13.651513  1.916663e+04
2   2.012000    0.726000   0.049000  145.664000  137.179000  5.026432e+06
3  40.966277    0.796364   0.213884    8.155052    7.126948  7.951364e+03
4  47.638579    0.599312   0.316321   25.907531   45.346692  7.765547e+04

     IntDen_std  %Area_mean  %Area_std  RawIntDen_mean  RawIntDen_std  \
0  2.821908e+03       100.0        0.0    2.257129e+03   2.821908e+03
1  2.647595e+04       100.0        0.0    1.916663e+04   2.647595e+04
2  5.020568e+06       100.0        0.0    5.026432e+06   5.020568e+06
3  1.173660e+04       100.0        0.0    7.951364e+03   1.173660e+04
4  2.235117e+05       100.0        0.0    7.765547e+04   2.235117e+05

   FeretX_mean  FeretX_std  FeretY_mean  FeretY_std  FeretAngle_mean  \
0   124.089109   57.843781    88.920792   51.956509       103.979446
1    96.469388   56.061956    74.387755   52.484329        98.199592
2    97.000000   97.000000     0.000000    0.000000       135.000000
3   100.389610   40.993239   103.298701   57.855410       100.865364
4    99.156250   52.276375    81.218750   50.956314       105.170656

   FeretAngle_std  MinFeret_mean  MinFeret_std   AR_mean    AR_std  \
0       47.466852       2.599564      1.875266  1.738505  0.579683
1       32.841924       6.559959      5.483810  2.445878  1.308504
2        0.000000     102.700000     97.300000  1.320500  0.316500
3       32.826527       4.046351      3.194558  2.004753  0.920000
4       32.194007      11.135063     19.819332  2.472656  1.591892

   Round_mean  Round_std  Solidity_mean  Solidity_std  num_spots_inverted  \
0    0.643267   0.218933       0.857396      0.144207                   2
1    0.527082   0.253666       0.789898      0.171918                   1
2    0.803500   0.192500       0.927500      0.059500                   6
3    0.585714   0.222167       0.852494      0.123426                   1
4    0.570969   0.297737       0.764094      0.196071                   7

   Mean_inverted  Median_inverted  Area_inverted_mean  Area_inverted_std  \
0        249.301              255        19553.000000       19551.000000
1        231.521              255        36317.000000           0.000000
2          3.678                0           96.166667          90.780719
3        239.694              255        37599.000000           0.000000
4        192.876              255         4322.142857       10305.987156

   X_inverted_mean  X_inverted_std  Y_inverted_mean  Y_inverted_std  \
0       149.373000       50.127000        81.072500       19.072500
1        99.125000        0.000000        98.020000        0.000000
2       116.399833       76.090823        63.316667       68.682097
3        99.823000        0.000000        99.313000        0.000000
4        84.919429       42.163829       101.338143       58.868357

   Perim._inverted_mean  Perim._inverted_std  BX_inverted_mean  \
0            405.556000           400.728000         99.500000
1            810.728000             0.000000          0.000000
2             39.361167            32.887105        112.666667
3            808.042000             0.000000          0.000000
4            420.444429           961.335095         67.000000

   BX_inverted_std  BY_inverted_mean  BY_inverted_std  Width_inverted_mean  \
0        99.500000         30.500000        30.500000           100.500000
1         0.000000          0.000000         0.000000           200.000000
2        75.770853         55.833333        68.594015             7.666667
3         0.000000          0.000000         0.000000           200.000000
4        48.296702         84.285714        64.853052            36.285714

   Width_inverted_std  Height_inverted_mean  Height_inverted_std  \
0           99.500000            101.000000            99.000000
1            0.000000            200.000000             0.000000
2            6.342099             15.166667            14.667614
3            0.000000            200.000000             0.000000
4           67.748936             35.000000            67.966378

   Major_inverted_mean  Major_inverted_std  Minor_inverted_mean  \
0           113.250500          110.993500             111.5785
1           216.098000            0.000000             213.9780
2            14.718667           13.570203               6.4865
3           219.495000            0.000000             218.1040
4            36.615143           68.951076              32.0290

   Minor_inverted_std  Angle_inverted_mean  Angle_inverted_std  \
0          110.450500           105.140500           15.140500
1            0.000000             6.379000            0.000000
2            4.905350            58.449500           33.195085
3            0.000000            13.637000            0.000000
4           62.839147            56.351429           65.399852

   Circ._inverted_mean  Circ._inverted_std  Feret_inverted_mean  \
0             0.878000            0.122000           142.539500
1             0.694000            0.000000           282.843000
2             0.754000            0.263463            16.280500
3             0.724000            0.000000           282.843000
4             0.745714            0.337601            49.510429

   Feret_inverted_std  IntDen_inverted_mean  IntDen_inverted_std  \
0          140.303500          4.986015e+06         4.985505e+06
1            0.000000          9.260835e+06         0.000000e+00
2           14.403171          2.452250e+04         2.314908e+04
3            0.000000          9.587745e+06         0.000000e+00
4           96.095328          1.102146e+06         2.628027e+06

   %Area_inverted_mean  %Area_inverted_std  RawIntDen_inverted_mean  \
0                100.0                 0.0             4.986015e+06
1                100.0                 0.0             9.260835e+06
2                100.0                 0.0             2.452250e+04
3                100.0                 0.0             9.587745e+06
4                100.0                 0.0             1.102146e+06

   RawIntDen_inverted_std  FeretX_inverted_mean  FeretX_inverted_std  \
0            4.985505e+06             99.500000            99.500000
1            0.000000e+00              0.000000             0.000000
2            2.314908e+04            114.500000            75.583839
3            0.000000e+00              0.000000             0.000000
4            2.628027e+06             67.714286            48.962710

   FeretY_inverted_mean  FeretY_inverted_std  FeretAngle_inverted_mean  \
0             30.500000            30.500000                125.782500
1              0.000000             0.000000                135.000000
2             70.000000            68.471405                 85.368333
3              0.000000             0.000000                135.000000
4             84.857143            65.627583                136.734000

   FeretAngle_inverted_std  MinFeret_inverted_mean  MinFeret_inverted_std  \
0                 9.217500              100.500000              99.500000
1                 0.000000              200.000000               0.000000
2                34.511534                7.389667               6.291349
3                 0.000000              200.000000               0.000000
4                 8.210170               34.848857              68.029623

   AR_inverted_mean  AR_inverted_std  Round_inverted_mean  Round_inverted_std  \
0          1.505000         0.495000             0.745000            0.245000
1          1.010000         0.000000             0.990000            0.000000
2          2.470333         2.450747             0.641333            0.259052
3          1.006000         0.000000             0.994000            0.000000
4          1.249286         0.436381             0.865714            0.189952

   Solidity_inverted_mean  Solidity_inverted_std
0                0.989000               0.011000
1                0.908000               0.000000
2                0.912833               0.070862
3                0.940000               0.000000
4                0.895286               0.102845
(13, 98)
[ 0.14765821  0.2103977   0.19482994  0.24405631  0.14133334 -2.6961794
 -0.2267239 ]

In [27]:
new_df

,path,feats_df,inverse_feats_df,num_spots,Mean,Median,Area_mean,Area_std,X_mean,X_std,Y_mean,Y_std,Perim._mean,Perim._std,BX_mean,BX_std,BY_mean,BY_std,Width_mean,Width_std,Height_mean,Height_std,Major_mean,Major_std,Minor_mean,Minor_std,Angle_mean,Angle_std,Circ._mean,Circ._std,Feret_mean,Feret_std,IntDen_mean,IntDen_std,%Area_mean,%Area_std,RawIntDen_mean,RawIntDen_std,FeretX_mean,FeretX_std,FeretY_mean,FeretY_std,FeretAngle_mean,FeretAngle_std,MinFeret_mean,MinFeret_std,AR_mean,AR_std,Round_mean,Round_std,Solidity_mean,Solidity_std,num_spots_inverted,Mean_inverted,Median_inverted,Area_inverted_mean,Area_inverted_std,X_inverted_mean,X_inverted_std,Y_inverted_mean,Y_inverted_std,Perim._inverted_mean,Perim._inverted_std,BX_inverted_mean,BX_inverted_std,BY_inverted_mean,BY_inverted_std,Width_inverted_mean,Width_inverted_std,Height_inverted_mean,Height_inverted_std,Major_inverted_mean,Major_inverted_std,Minor_inverted_mean,Minor_inverted_std,Angle_inverted_mean,Angle_inverted_std,Circ._inverted_mean,Circ._inverted_std,Feret_inverted_mean,Feret_inverted_std,IntDen_inverted_mean,IntDen_inverted_std,%Area_inverted_mean,%Area_inverted_std,RawIntDen_inverted_mean,RawIntDen_inverted_std,FeretX_inverted_mean,FeretX_inverted_std,FeretY_inverted_mean,FeretY_inverted_std,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std,pred_params
0,LF10_11-20-23_(green)_(0-152).tif.csv,Label ...,Label Area...,101,5.699,0,8.851485,11.066304,125.673327,57.972907,88.902515,52.059334,10.451525,8.653331,123.960396,57.832452,87.297030,52.027705,3.435644,2.619107,3.188119,2.423944,3.860287,2.502460,2.196881,1.250776,50.320287,53.900986,0.857059,0.194583,4.505861,3.106018,2.257129e+03,2.821908e+03,100.0,0.0,2.257129e+03,2.821908e+03,124.089109,57.843781,88.920792,51.956509,103.979446,47.466852,2.599564,1.875266,1.738505,0.579683,0.643267,0.218933,0.857396,0.144207,2,249.301,255,19553.000000,19551.000000,149.373000,50.127000,81.072500,19.072500,405.556000,400.728000,99.500000,99.500000,30.500000,30.500000,100.500000,99.500000,101.000000,99.000000,113.250500,110.993500,111.578500,110.450500,105.140500,15.140500,0.878000,0.122000,142.539500,140.303500,4.986015e+06,4.985505e+06,100.0,0.0,4.986015e+06,4.985505e+06,99.500000,99.500000,30.500000,30.500000,125.782500,9.217500,100.500000,99.500000,1.505000,0.495000,0.745000,0.245000,0.989000,0.011000,"[0.07444812, 0.1587155, 0.16584946, 0.14243883..."
1,mpar_rto(c-c)_(green)_(0-137).tif.csv,Label Ar...,Label Area...,49,23.479,0,75.163265,103.827240,99.147755,55.940428,74.931612,51.325268,36.572388,37.781366,95.387755,55.720445,68.224490,47.695576,7.571429,6.676184,13.428571,13.490738,12.331796,11.379018,5.113531,3.973676,73.345184,38.726102,0.654939,0.264055,14.381224,13.651513,1.916663e+04,2.647595e+04,100.0,0.0,1.916663e+04,2.647595e+04,96.469388,56.061956,74.387755,52.484329,98.199592,32.841924,6.559959,5.483810,2.445878,1.308504,0.527082,0.253666,0.789898,0.171918,1,231.521,255,36317.000000,0.000000,99.125000,0.000000,98.020000,0.000000,810.728000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,216.098000,0.000000,213.978000,0.000000,6.379000,0.000000,0.694000,0.000000,282.843000,0.000000,9.260835e+06,0.000000e+00,100.0,0.0,9.260835e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.010000,0.000000,0.990000,0.000000,0.908000,0.000000,"[0.07012652, 0.16461392, 0.16871558, 0.1352927..."
2,mpar_rto_crispr_(green)_(0-155).tif.csv,Label Ar...,Label Ar...,2,251.322,255,19711.500000,19688.500000,148.632000,49.216000,51.684500,49.271500,437.255000,417.941000,97.000000,97.000000,0.000000,0.000000,103.000000,97.000000,103.000000,97.000000,115.674500,108.751500,113.879500,109.649500,124.750000,2.012000,0.726000,0.049000,145.664000,137.179000,5.026432e+06,5.020568e+06,100.0,0.0,5.026432e+06,5.020568e+06,97.000000,97.000000,0.000000,0.000000,135.000000,0.000000,102.700000,97.300000,1.320500,0.316500,0.803500,0.192500,0.927500,0.059500,6,3.678,0,96.166667,90.780719,116.399833,76.090823,63.316667,68.682097,39.361167,32.887105,112.666667,75.770853,55.833333,68.594015,7.666667,6.342099,15.166667,14.667614,14.718667,13.570203,6.486500,4.905350,58.449500,33.195085,0.754000,0.263463,16.280500,14.403171,2.452250e+04,2.314908e+04,100.0,0.0,2.452250e+04,2.314908e+04,114.500000,75.583839,70.000000,68.471405,85.368333,34.511534,7.389667,6.291349,2.470333,2.450747,0.641333,0.259052,0.912833,0.070862,"[0.14765821, 0.2103977, 0.19482994, 0.24405631..."
3,MLC_F1_11-20-23_(green)_(0-105).tif.csv,Label ...,Label Ar...,77,15.306,0,31.181818,46.025890,101.898026,40.868593,104.009818,57.481703,19.575195,18.250837,99.701299,41.001763,100.246753,57.180315,4.337662,3.451370,7.363636,7.059872,7.314792,6.449969,3.544974,2.646633,75.761312,40.966277,0.796364,0.213884,8.155052,7.126948,7.951364e+03,1.173660e+04,100.0,0.0,7.951364e+03,1.173660e+04,100.389610,40.993239,103.298701,57.855410,100.865364,32.826527,4.046351,3.194558,2.004753,0.920000,0.585714,0.222167,0.852494,0.123426,1,239.694,255,37599.000000,0.000000,99.823000,0.000000,99.313000,0.000000,808.042000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,219.495000,0.000000,218.104000,0.000000,13.637000,0.000000,0.724000,0.000000,282.843000,0.000000,9.587745e+06,0.000000e+00,100.0,0.0,9.587745e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.006000,0.000000,0.994000,0.000000,0.940000,0.000000,"[0.07204828, 0.17388527, 0.1414945, 0.13030724..."
4,RTO_rnai_med_(green)_(0-109).tif.csv,Label Are...,Label Area ...,32,62.124,0,304.531250,876.516507,104.642344,49.916328,82.908906,45.964830,98.939469,229.053596,97.843750,52.672994,69.250000,46.896828,13.187500,23.177896,23.937500,43.999956,18.785969,27.853125,7.510688,11.242490,71.322094,47.638579,0.599312,0.316321,25.907531,45.346692,7.765547e+04,2.235117e+05,100.0,0.0,7.765547e+04,2.235117e+05,99.156250,52.276375,81.218750,50.956314,105.170656,32.194007,11.135063,19.819332,2.472656,1.591892,0.570969,0.297737,0.764094,0.196071,7,192.876,255,4322.142857,10305.987156,84.919429,42.163829,101.338143,58.868357,420.444429,961.335095,67.000000,48.296702,84.285714,64.853052,36.285714,67.748936,35.000000,67.966378,36.615143,68.951076,32.029000,62.839147,56.351429,65.399852,0.745714,0.337601,49.510429,96.095328,1.102146e+06,2.628027e+06,100.0,0.0,1.102146e+06,2.628027e+06,67.714286,48.962710,84.857143,65.627583,136.734000,8.210170,34.848857,68.029623,1.249286,0.436381,0.865714,0.189952,0.895286,0.102845,"[0.073866464, 0.09276281, 0.14801314, 0.103877..."
5,NEGAN_crispr_(green)_(0-150).tif.csv,Label Area ...,Label Area ...,0,0.000,0,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,800.000000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.785000,0.000000,282.843000,0.000000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000e+00,100.0,0.0,1.020000e+07,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,"[0.14634633, 0.21512721, 0.19381776, 0.2353293..."
6,mpar_wt_(green)_(0-170).tif.csv,Label Area ...,Label Area M...,66,8.077,0,19.196970,18.371767,97.896258,52.566051,95.364621,53.682640,15.332273,9.204770,95.500000,52.587085,92.939394,53.159816,4.878788,2.549600,4.939394,3.370454,5.807909,3.168420,3.409803,1.759495,92.356000,57.595572,0.861833,0.154268,6.494227,3.458627,4.895227e+03,4.684800e+03,100.0,0.0,4.895227e+03,4.684800e+03,95.833333,52.615697,95.484848,54.545572,111.274424,46.307654,3.805500,1.983291,1.763136,0.530357,0.614000,0.165891,0.844894,0.093472,1,246.923,255,38733.000000,0.000000,100.011000,0.000000,99.631000,0.000000,843.012000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,222.529000,0.000000,221.618000,0.000000,5.282000,0.000000,0.685000,0.000000,282.843000,0.000000,9.876915e+06,0.000000e+00,100.0,0.0,9.876915e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.004000,0.000000,0.996000,0.000000,0.968000,0.000000,"[0.0768711, 0.16447178, 0.15797749, 0.1304044,..."
7,RTO_rnai_low_(green)_(0-115).tif.csv,Label Are...,Label Area ...,91,13.528,0,23.318681,39.296808,107.970220,46.996468,83.078824,52.120805,18.276022,18.081455,105.923077,47.434913,79.659341,50.818838,4.076923,3.604731,6.835165,6.696339,6.655802,5.625546,3.008747,2.487333,72.963319,41.886223,0.743527,0.243147,7.635242,6.819511,5.946264e+03,1.002069e+04,100.0,0.0,5.946264e+03,1.002069e+04,106.329670,47.511492,82.648352,52.371952,99.644407,34.345456,3.593000,3.210409,2.311527,1.326418,0.542692,0.229538,0.818934,0.136272,1,241.472,255,37878.000000,0.000000,100.297000,0.000000,98.801000,0.000000,825.213000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,220.784000,0.000000,218.439000,0.000000,175.665000,0.000000,0.699000,0.000000,282.843000,0.000000,9.658890e+06,0.000000e+00,100.0,0.0,9.658890e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.011000,0.000000,0.989000,0.000000,0.947000,0.000000,"[0.06952988, 0.16020426, 0.13923697, 0.1441595..."
8,bHLH2_RNAi_(green)_(0-170).tif.csv,Label Area M...,Label Area M...,0,0.000,0,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,800.000000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.785000,0.000000,282.843000,0.000000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000e+00,100.0,0.0,1.020000e+07,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,"[0.14634633, 0.21512721, 0.19381776, 0.2353293..."
9,RTO_rnai_high_(green)_(0-103).tif.csv,Label Ar...,Label Ar...,11,128.246,255,1828.818182,5677.547083,113.048091,65.100510,40.077091,42.948935,195.803364,544.507525,101.090909,73.301934,28.545455,39.326983,23.636364,53.290410,22.545455,56.343691,21.421909,46.851991,16.473273,42.294751,23.064273,37.259117,0.671182,0.350863,30.750000,72.401649,4.663486e+05,1.447775e+06,100.0,0.0,4.663486e+05,1.447775e+06,101.454545,73.523483,31.000000,38.083640,121.365909,41.616273,20.817909,53.213065,1.915636,1.217189,0.704182,0.314290,0.854727,0.196756,48,126.754,0,414.229167,1530.426768,100.006062,44.350497,69.618417,54.639683,71.881896,211.143185,94.250000,44.247175,61.000000,56.220177,10.562500,22.046264,16.791667,42.311325,15.150167,32.905507,7.268125,13.323091,66.951479,58.625727,0.826000,0.264367,19.489729,46.431683,1.056284e+05,3.902588e+05,100.0,0.0,1.056284e+05,3.902588e+05,95.333333,44.349621,68.645833,58.593405,117.005208,35.754028,9.485479,20.990371,1.680583,1.042379,0.696771,0.219777,0.882354,0.131232,"[0.149471, 0.20811103, 0.18854679, 0.2429812, ..."
10,F2_260_green)_(0-105).tif.csv,Label Area M...,Label Area Mea...,26,70.966,0,428.153846,519.658223,103.716385,53.872307,86.366654,56.292048,99.326923,90.300749,95.576923,54.687344,69.500000,53.847541,17.000000,14.665501,35.038462,27.607804,32.030154,22.516273,11.821077,7.936903,83.427346,31.445279,0.545500,0.229855,37.386077,29.418346,1.091792e+05,1.325128e+05,100.0,0.0,1.091792e+05,1.325128e+05,98.538462,54.670503,87.961538,54.263234,93.984962,27.368451,14.872077,11.791365,2.686885,0.910115,0.428462,0.185528,0.807885,0.137202,1,184.034,255,28868.000000,0.000000,101.886000,0.000000,101.155000,0.000000,1845.727000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,195.203000,0.000000,188.295000,0.000000,60.677000,0.000000,0.106000,0.000000,282.843000,0.000000,7.361340e+06,0.000000e+00,100.0,0.0,7.361340e+06,0.000000e+00,0.000000,0.000000,200.000000,0.000000,45.000000,0.000000,200.000000,0.000000,1.037000,0.000000,0.965000,0.000000,0.723000,0.000000,"[0.064765364, 0.094491005, 0.15846394, 0.12413..."
11,F2_A 8_(green)_(0-100).tif.csv,Label Area M...,Label Area Me...,9,92.578,0,1613.555556,771.210752,114.434444,60.967917,98.298000,56.395622,235.716333,119.683538,93.333333,65.540488,62.000000,57.263523,43.000000,19.275776,78.555556,47.211371,81.267444,47.188854,24.941556,8.592435,80.759444,34.770839,0.419333,0.157302,87.077667,46.327773,4.114567e+05,1.966587e+05,100.0,0.0,4.114567e+05,1.966587e+05,98.222222,67.698314,88.777778,79.286790,88.086333,29.493138,32.186333,11.473686,3.590667,2.847227,0.372111,0.136953,0.766111,0.104342,4,162.422,255,6369.500000,11016.133407,113.921750,36.502635,37.842750,38.755926,479.377250,810.326836,86.500000,61.210702,11.250000,11.903256,53.500000,84.600532,52.000000,85.460517,49.878750,77.320383,45.701250,75.428649,40.201750,63.391093,0.592500,0.326511,71.400250,114.144371,1.624222e+06,2.809114e+06,100.0,0.0,1.624222e+06,2.809114e+06,86.500000,61.210702,61.250000,80.726003,122.534750,48.099984,51.817750,85.561271,2.398750,1.626927,0.638000,0.348958,0.849000,0.154614,"[0.14820443, 0.19487068, 0.1944198, 0.24322198..."
12,bHLH2_OE_(green)_(0-141_thresh.tif.csv,Label A...,Label Are...,30,67.001,0,350.333333,436.638320,104.649567,63.380542,69.287167,49.347736,105.791967,105.323220,95.300000,64.799254,54.300000,45.721002,18.366667,14.716166,31.333333,28.248107,28.469100,22.259388,11.132167,7.572338,95.829533,41.340200,0.519500,0.271161,34.549767,29.326032,8.933500e+04,1.113428e+05,100.0,0.0,8.933500e+04,1.113428e+05,97.966667,65.061757,61.133333,49.947795,106.094367,30.422104,14.895000,11.599036,2.534433,1.161018,0.472233,0.188002,0.736767,0.158909,3,187.999,255,9830.000000,13840.207585,95.572667,64.063517,36.149333,47.039893,479.711333,643.458785,59.666667,76.054074,0.000000,0.000000,72.333333,90.282273,71.000000,91.224997,70.875333,88.047917,67.994000,87.418781,165.417333,15.370366,0.643667,0.321746,100.305000,128.089096,2.506650e+06,3.529253e+06,100.0,0.0,2.506650e+06,3.529253e+06,59.666667,76.054074,67.000000,94.046088,118.021000,52.215878,71.000000,91.224997,1.264667,0.176532,0.808000,0.123701,0.839333,0.073436,"[0.06989242, 0.10823366, 0.15282317, 0.1045716..."

In [32]:
## TODO: Grab dataframe at the top (w/ all the features), drop all unnessesary columns (diff. from real_df, drop parameters)
## choose first five images and run it and see how close they are. 

print ("Ua","Ui","Ga","Gi","Da","Di","Ba")
for i in range(new_df.shape[0]):
  print(new_df["path"][i])
  print(new_df["pred_params"][i])
  #print(new_df["Ua"][i], new_df["Ui"][i],new_df["Ga"][i], new_df["Gi"][i],new_df["Da"][i], new_df["Di"][i],new_df["Ba"][i]

Ua Ui Ga Gi Da Di Ba
LF10_11-20-23_(green)_(0-152).tif.csv
[ 0.07444812  0.1587155   0.16584946  0.14243883  0.04621829  0.7816448
 -0.12434022]
mpar_rto(c-c)_(green)_(0-137).tif.csv
[ 0.07012652  0.16461392  0.16871558  0.13529272  0.04601083  0.8899547
 -0.119705  ]
mpar_rto_crispr_(green)_(0-155).tif.csv
[ 0.14765821  0.2103977   0.19482994  0.24405631  0.14133334 -2.6961794
 -0.2267239 ]
MLC_F1_11-20-23_(green)_(0-105).tif.csv
[ 0.07204828  0.17388527  0.1414945   0.13030724  0.04593876  4.1902494
 -0.1415103 ]
RTO_rnai_med_(green)_(0-109).tif.csv
[ 0.07386646  0.09276281  0.14801314  0.10387754  0.04547361  1.1544236
 -0.13415183]
NEGAN_crispr_(green)_(0-150).tif.csv
[ 0.14634633  0.21512721  0.19381776  0.2353293   0.14035179  4.2921557
 -0.25183842]
mpar_wt_(green)_(0-170).tif.csv
[ 0.0768711   0.16447178  0.15797749  0.1304044   0.04629316  3.3565116
 -0.14158332]
RTO_rnai_low_(green)_(0-115).tif.csv
[ 0.06952988  0.16020426  0.13923697  0.14415951  0.04632314  2.4976082
 -0.13223407]
bHLH2_RNAi_(green)_(0-170).tif.csv
[ 0.14634633  0.21512721  0.19381776  0.2353293   0.14035179  4.2921557
 -0.25183842]
RTO_rnai_high_(green)_(0-103).tif.csv
[ 0.149471    0.20811103  0.18854679  0.2429812   0.14168325  0.5057017
 -0.2380946 ]
F2_260_green)_(0-105).tif.csv
[ 0.06476536  0.094491    0.15846394  0.12413167  0.04572761  1.0497221
 -0.10041291]
F2_A 8_(green)_(0-100).tif.csv
[ 0.14820443  0.19487068  0.1944198   0.24322198  0.14173828  0.9666604
 -0.2530404 ]
bHLH2_OE_(green)_(0-141_thresh.tif.csv
[ 0.06989242  0.10823366  0.15282317  0.10457169  0.04700283  0.887137
 -0.12759888]