<a href="https://colab.research.google.com/github/vcellmike/PatternsFormation/blob/main/Working/Data_loader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade pip
!pip install torch

Requirement already satisfied: pip in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (25.2)
Requirement already satisfied: torch in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (2.8.0)
Requirement already satisfied: filelock in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from torch) (80.7.1)
Requirement already satisfied: sympy>=1.13.3 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from torch) (2025.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from jinja2->torch) (3.0.2)

In [2]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (1.7.1)
Requirement already satisfied: numpy>=1.22.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.8.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

In [3]:
!pip install Pillow
!pip install pandas
!pip install matplotlib

Requirement already satisfied: Pillow in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (11.1.0)
Requirement already satisfied: pandas in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/reeshapatel/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [4]:
import json
import os
import torch
from sklearn.metrics import accuracy_score, classification_report
from PIL import Image
import pandas as pd
from PIL import Image
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import pickle
pd.set_option('display.max_columns', None)

In [6]:
# unzip the VCell simulation images
!tar -xf "data/all_images.zip" -C '/Users/reeshapatel/software1/temp'
#!tar -xf "/Users/mikhailblinov/Software/PatternsFormation/Toybox/05-09-2024_all_images.zip" -C '/Users/mikhailblinov/Software/Temp'
#!tar -xf "/Users/mikhailblinov/Software/PatternsFormation/Toybox/Generated Images.zip" -C '/Users/mikhailblinov/Software/Temp'
#!tar -xf "/Users/mikhailblinov/Software/PatternsFormation/Toybox/Generated_Images_7-2-24.zip" -C '/Users/mikhailblinov/Software/Temp'
!echo Unzip Complete

Unzip Complete

In [7]:
# downgrade numpy to open pickle files
# Numpy: 2.0.2
# Pickle Highest Protocol: 5 (no need to change)
# Pickle Default Protocol: 4 (no need to change)

!pip uninstall --yes numpy
!pip install numpy==2.0.2

Found existing installation: numpy 2.0.2
Uninstalling numpy-2.0.2:
  Successfully uninstalled numpy-2.0.2
Collecting numpy==2.0.2
  Using cached numpy-2.0.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (114 kB)
Using cached numpy-2.0.2-cp312-cp312-macosx_11_0_arm64.whl (13.5 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
molclustpy 0.1.0 requires bionetgen, which is not installed.
Successfully installed numpy-2.0.2

In [3]:
# import features dataframe for all the images
with open("data/unclassified_features.pkl", 'rb') as f:
  feats_df = pickle.load(f) # deserialize using load()

print(feats_df.shape)

feats_df

(39517, 111)

,Ua,Ui,Ga,Gi,Ba,Da,Di,pattern,noise,path,seed,dir,feat_bool,num_spots,Mean,Median,Area_mean,Area_std,X_mean,X_std,Y_mean,Y_std,Perim._mean,Perim._std,BX_mean,BX_std,BY_mean,BY_std,Width_mean,Width_std,Height_mean,Height_std,Major_mean,Major_std,Minor_mean,Minor_std,Angle_mean,Angle_std,Circ._mean,Circ._std,Feret_mean,Feret_std,IntDen_mean,IntDen_std,%Area_mean,%Area_std,RawIntDen_mean,RawIntDen_std,FeretX_mean,FeretX_std,FeretY_mean,FeretY_std,FeretAngle_mean,FeretAngle_std,MinFeret_mean,MinFeret_std,AR_mean,AR_std,Round_mean,Round_std,Solidity_mean,Solidity_std,num_spots_inverted,Mean_inverted,Median_inverted,Area_inverted_mean,Area_inverted_std,X_inverted_mean,X_inverted_std,Y_inverted_mean,Y_inverted_std,Perim._inverted_mean,Perim._inverted_std,BX_inverted_mean,BX_inverted_std,BY_inverted_mean,BY_inverted_std,Width_inverted_mean,Width_inverted_std,Height_inverted_mean,Height_inverted_std,Major_inverted_mean,Major_inverted_std,Minor_inverted_mean,Minor_inverted_std,Angle_inverted_mean,Angle_inverted_std,Circ._inverted_mean,Circ._inverted_std,Feret_inverted_mean,Feret_inverted_std,IntDen_inverted_mean,IntDen_inverted_std,%Area_inverted_mean,%Area_inverted_std,RawIntDen_inverted_mean,RawIntDen_inverted_std,FeretX_inverted_mean,FeretX_inverted_std,FeretY_inverted_mean,FeretY_inverted_std,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std
0,0.011652,0.1066,0.115805,0.061599,-0.043244,0.007928,0.559698,0,2,0.png,0,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
1,0.025122,0.063822,0.071957,0.106327,-0.113131,0.009186,0.611871,1,2,1.png,1,/content/Images3/,1,70,5.489,0,12.300000,2.548669,99.395943,58.506181,97.530229,58.913237,12.282143,1.400962,97.371429,58.453442,95.528571,58.843551,4.071429,0.723512,4.057143,0.753766,4.245571,0.439294,3.664200,0.511781,55.108900,57.413924,0.958686,0.069883,4.926700,0.412294,3.136500e+03,649.910626,100.0,0.0,3.136500e+03,649.910626,97.942857,58.572760,96.014286,58.843981,120.129000,30.775307,3.653171,0.564778,1.177686,0.183575,0.866686,0.115368,0.879486,0.067138,1,249.511,255,39139.0,0.0,99.998,0.0,100.022,0.0,811.882,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.351,0.0,223.117,0.0,38.796,0.0,0.746,0.0,282.843,0.0,9980445.0,0.0,100.0,0.0,9980445.0,0.0,0.0,0.0,200.0,0.0,45.000,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.979,0.0
2,0.014455,0.085124,0.091124,0.113974,-0.060333,0.001776,1.798215,0,2,2.png,2,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
3,0.034475,0.059956,0.080798,0.10037,-0.132577,0.008852,0.854084,1,2,3.png,3,/content/Images3/,1,63,4.921,0,12.253968,2.569468,101.800571,59.297600,99.451270,58.953924,11.663270,1.365051,99.968254,59.323693,97.619048,58.964458,3.666667,0.534522,3.666667,0.534522,4.237317,0.401713,3.661714,0.572434,56.049556,60.605082,0.999619,0.003000,4.908365,0.491745,3.124762e+03,655.214389,100.0,0.0,3.124762e+03,655.214389,100.158730,59.330446,98.079365,59.017431,120.191190,32.406426,3.476190,0.613529,1.185032,0.226780,0.867667,0.127976,0.954905,0.046408,1,250.078,255,39228.0,0.0,99.992,0.0,100.015,0.0,809.255,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.524,0.0,223.451,0.0,72.380,0.0,0.753,0.0,282.843,0.0,10003140.0,0.0,100.0,0.0,10003140.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.981,0.0
4,0.025569,0.143322,0.154726,0.025138,-0.067635,0.009413,1.87632,0,2,4.png,4,/content/Images3/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39512,0.047659,0.179187,0.122823,0.048745,-0.080442,0.011393,0.468993,0,3,noise 3 21522.0.png,21522.0,/content/Images1/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
39513,0.049658,0.087822,0.124444,0.105756,-0.140723,0.008773,1.001359,1,7,noise 7 21167.0.png,21167.0,/content/Images1/,1,190,20.432,0,16.868421,6.457028,100.172684,60.349015,100.478663,60.466797,13.893874,3.242651,98.136842,60.320828,98.426316,60.466801,4.068421,1.000291,4.094737,0.968707,5.003858,1.036639,4.157695,0.984516,33.517868,46.384302,0.994784,0.019226,5.803453,1.167055,4.301447e+03,1646.542193,100.0,0.0,4.301447e+03,1646.542193,98.142105,60.326182,98.668421,60.523250,130.262679,20.839286,3.715789,0.902198,1.235379,0.260330,0.839895,0.149162,0.995163,0.019281,1,234.568,255,36795.0,0.0,100.018,0.0,99.958,0.0,906.818,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,216.515,0.0,216.377,0.0,157.111,0.0,0.562,0.0,281.432,0.0,9382725.0,0.0,100.0,0.0,9382725.0,0.0,0.0,0.0,0.0,0.0,135.288,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.920,0.0
39514,0.025269,0.096806,0.0973,0.124239,-0.046031,0.008247,0.752525,0,5,noise 5 21035.0.png,21035.0,/content/Images1/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
39515,0.029474,0.085933,0.103994,0.103636,-0.119675,0.008054,1.058641,1,3,noise 3 24575.0.png,24575.0,/content/Images1/,1,147,52.288,0,55.795918,24.605165,100.047367,58.893051,96.111347,60.325679,25.775707,6.183994,96.156463,58.864043,92.265306,60.226819,7.768707,1.814784,7.673469,1.955850,8.922531,1.984367,7.614544,1.959629,54.301395,55.166164,0.985673,0.030430,9.755361,2.165780,1.422796e+04,6274.317014,100.0,0.0,1.422796e+04,6274.317014,96.748299,58.943285,94.911565,60.747042,107.074156,43.168660,7.184980,1.867690,1.206456,0.255365,0.856463,0.133632,0.953762,0.021174,1,202.712,255,31798.0,0.0,100.031,0.0,100.003,0.0,958.860,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,201.304,0.0,201.121,0.0,142.081,0.0,0.435,0.0,282.843,0.0,8108490.0,0.0,100.0,0.0,8108490.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.795,0.0
39516,0.019996,0.117955,0.161475,0.075774,-0.063299,0.009488,0.414752,0,4,noise 4 24351.0.png,24351.0,/content/Images1/,1,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000,100.0,0.0,1.020000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0,0.000,0,40000.0,0.0,100.000,0.0,100.000,0.0,800.000,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,225.676,0.0,225.676,0.0,0.000,0.0,0.785,0.0,282.843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0

In [29]:
# compare all pkl files
file1 = "data/manual_classification_cl6.pkl"
# file1 originally named 2024-08-15_manual_classification.pkl

file2 = "data/2024-08-18_curr_df.pkl"
# file2 - CNN classification

file3 = "data/2024-08-19_feat_array_unscaled.pkl"

file4 = "data/2024-08-19_feats_df_narrow.pkl"
# file4 - unclassified_features shortened

file5 = "data/2025-05-24_feats_df_toybox.pkl"

file6 = "data/Images_Classified.pkl"
# file6 - 27515 images and 113 columns - fullpath, classifier_pred_class

file7 = "data/manual_classification.pkl"

file8 = "data/single_param_scans.pkl"

file9 = "data/unclassified_features.pkl"

file10 = "data/random_indices_array.pkl"
# file10 - originally named "2024-08-11_random_indices_array.pkl"

file11 = "../OlderStuff/2024-08-11_manual_classification.pkl"

In [43]:
with open(file11, 'rb') as f:
  df = pickle.load(f)

print(df.shape)
df

df_none = df[df['class'] == 'None']
df_none
print(df_none.shape)

(39517, 5)
(13241, 5)

In [26]:
# function to compare data frames and dictionaries
def compare_data_structures(ds1, ds2, f1, f2):
    if isinstance(ds1, pd.DataFrame) and isinstance(ds2, pd.DataFrame):
        print("Both are DataFrames")
        comparison = ds1.equals(ds2)
        print(f"DataFrames are equal: {comparison}")
    elif isinstance(ds1, dict) and isinstance(ds2, dict):
        print("Both are Dictionaries")
        keys1 = set(ds1.keys())
        keys2 = set(ds2.keys())
        common_keys = keys1.intersection(keys2)
        for key in common_keys:
            if ds1[key] != ds2[key]:
                print(f"Difference in key '{key}': {ds1[key]} != {ds2[key]}")
    else:
        print(f1, "is type", type(ds1))
        print(f2, "is type", type(ds2))


def find_identical_rows(df1, df2, key_columns=None):
    identical_rows = pd.merge(df1, df2, how='inner', on=key_columns) # key_columns is a list of columns to match on
    return identical_rows


# Example usage:
with open("data/2024-08-15_curr_df.pkl", 'rb') as f1, open(file2, 'rb') as f2:
    ds1 = pickle.load(f1)
    ds2 = pickle.load(f2)
    compare_data_structures(ds1, ds2, f1, f2)

ds1.head()
ds2.head()

Both are DataFrames
DataFrames are equal: False

  class noise   path seed                dir  pred_class        pc1        pc2
0     2     2  0.png    0  /content/Images3/           1 -31.683971 -14.198348
1  None     2  1.png    1  /content/Images3/           2  31.977729 -17.444531
2     2     2  2.png    2  /content/Images3/           1 -31.683971 -14.198348
3  None     2  3.png    3  /content/Images3/           2  31.347501 -16.048195
4     2     2  4.png    4  /content/Images3/           1 -31.683971 -14.198348