<a href="https://colab.research.google.com/github/vcellmike/PatternsFormation/blob/main/Working/2024_08_21_XGBoost_on_ImageJ_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install xgboost

import json
import os
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from sklearn.metrics import accuracy_score, classification_report
from transformers import AutoModel, AutoTokenizer, get_scheduler
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from torch.optim import AdamW
from tqdm.notebook import tqdm, trange
from time import perf_counter
from PIL import Image
import pandas as pd
#from google.colab import drive
from PIL import Image
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import pickle

print("All dependencies present.")

Collecting xgboost
  Downloading xgboost-3.1.1-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\user.sr7872\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\user.sr7872\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.1.1-py3-none-win_amd64.whl (72.0 MB)
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   - -------------------------------------- 2.1/72.0 MB 13.2 MB/s eta 0:00:06
   ----- ---------------------------------- 9.4/72.0 MB 23.7 MB/s eta 0:00:03
   --------- ------------------------------ 16.3/72.0 MB 21.8 MB/s eta 0:00:03
   --------------- ------------------------ 27.5/72.0 MB 27.5 MB/s eta 0:00:02
   ------------------ --------------------- 32.8/72.0 MB 25.7 MB/s eta 0:00:02
   --------------------- ------------------ 38.5/72.0 MB 25.8 MB/s eta 0:00:02
   ------------------------ --------------- 44.8/72.0 MB 25.7 MB/s eta 0:00:02
   ------------------------- -------------- 46.7/72.0 MB 22.3 MB/s eta 0:00:02
   -------------------------- ------------- 47.4/72.0 MB 19.7 MB/s eta 0:00:02
   -------------------------- ------------- 48.2/72.0 MB 18.1 MB/s eta 0:00:02
   --------------------------- ------------ 50.1/72.0 MB 16.7 MB/s eta 0:00:02
   ------------------------------ --------- 55.6/72.0 MB 15.9 MB/s eta 0:00:02
   ------------------------------- -------- 56.4/72.0 MB 15.1 MB/s eta 0:00:02
   -------------------------------- ------- 57.9/72.0 MB 14.5 MB/s eta 0:00:01
   -------------------------------- ------- 59.2/72.0 MB 13.8 MB/s eta 0:00:01
   --------------------------------- ------ 60.3/72.0 MB 13.3 MB/s eta 0:00:01
   --------------------------------- ------ 61.1/72.0 MB 12.9 MB/s eta 0:00:01
   ---------------------------------- ----- 62.4/72.0 MB 12.5 MB/s eta 0:00:01
   ----------------------------------- ---- 63.7/72.0 MB 12.2 MB/s eta 0:00:01
   ------------------------------------ --- 65.3/72.0 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  70.8/72.0 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------  71.8/72.0 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------  71.8/72.0 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------  71.8/72.0 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------- 72.0/72.0 MB 11.2 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.1.1

ModuleNotFoundError: No module named 'torch'

In [ ]:
# set random seeds for repeatability
import numpy as np
import random

def set_seed(seed_val):
    random.seed(seed_val)
    np.random.seed(seed_val)
    torch.manual_seed(seed_val)
    torch.cuda.manual_seed_all(seed_val)

print("Seed set")

Seed set

In [ ]:
seed_val = 42
set_seed(seed_val)

In [ ]:
file_in = "data/Images_Classified_np126"

with open(file_in + '.pkl', 'rb') as f:
    feats_df = pickle.load(f)

#load in dataframe
pd.set_option('display.max_columns', None)

file_out = file_in + "_s" + str(seed_val) + "_XGB" + ".model"

print(file_out)
print(feats_df.shape)

feats_df.head()

data/Images_Classified_np126_s42_XGB.model
(27515, 113)

,Ua,Ui,Ga,Gi,Ba,Da,Di,pattern,noise,path,seed,dir,feat_bool,num_spots,Mean,Median,Area_mean,Area_std,X_mean,X_std,Y_mean,Y_std,Perim._mean,Perim._std,BX_mean,BX_std,BY_mean,BY_std,Width_mean,Width_std,Height_mean,Height_std,Major_mean,Major_std,Minor_mean,Minor_std,Angle_mean,Angle_std,Circ._mean,Circ._std,Feret_mean,Feret_std,IntDen_mean,IntDen_std,%Area_mean,%Area_std,RawIntDen_mean,RawIntDen_std,FeretX_mean,FeretX_std,FeretY_mean,FeretY_std,FeretAngle_mean,FeretAngle_std,MinFeret_mean,MinFeret_std,AR_mean,AR_std,Round_mean,Round_std,Solidity_mean,Solidity_std,num_spots_inverted,Mean_inverted,Median_inverted,Area_inverted_mean,Area_inverted_std,X_inverted_mean,X_inverted_std,Y_inverted_mean,Y_inverted_std,Perim._inverted_mean,Perim._inverted_std,BX_inverted_mean,BX_inverted_std,BY_inverted_mean,BY_inverted_std,Width_inverted_mean,Width_inverted_std,Height_inverted_mean,Height_inverted_std,Major_inverted_mean,Major_inverted_std,Minor_inverted_mean,Minor_inverted_std,Angle_inverted_mean,Angle_inverted_std,Circ._inverted_mean,Circ._inverted_std,Feret_inverted_mean,Feret_inverted_std,IntDen_inverted_mean,IntDen_inverted_std,%Area_inverted_mean,%Area_inverted_std,RawIntDen_inverted_mean,RawIntDen_inverted_std,FeretX_inverted_mean,FeretX_inverted_std,FeretY_inverted_mean,FeretY_inverted_std,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std,full_path,classifier_pred_class
0,0.025122,0.063822,0.071957,0.106327,-0.113131,0.009186,0.611871,1,2,1.png,1,/content/Images3,1,70,5.489,0,12.300000,2.548669,99.395943,58.506181,97.530229,58.913237,12.282143,1.400962,97.371429,58.453442,95.528571,58.843551,4.071429,0.723512,4.057143,0.753766,4.245571,0.439294,3.664200,0.511781,55.108900,57.413924,0.958686,0.069883,4.926700,0.412294,3136.500000,649.910626,100.0,0.0,3136.500000,649.910626,97.942857,58.572760,96.014286,58.843981,120.129000,30.775307,3.653171,0.564778,1.177686,0.183575,0.866686,0.115368,0.879486,0.067138,1,249.511,255,39139.0,0.0,99.998,0.0,100.022,0.0,811.882,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.351,0.0,223.117,0.0,38.796,0.0,0.746,0.0,282.843,0.0,9980445.0,0.0,100.0,0.0,9980445.0,0.0,0.0,0.0,200.0,0.0,45.0,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.979,0.0,/content/Images3/1.png,2
1,0.034475,0.059956,0.080798,0.10037,-0.132577,0.008852,0.854084,1,2,3.png,3,/content/Images3,1,63,4.921,0,12.253968,2.569468,101.800571,59.297600,99.451270,58.953924,11.663270,1.365051,99.968254,59.323693,97.619048,58.964458,3.666667,0.534522,3.666667,0.534522,4.237317,0.401713,3.661714,0.572434,56.049556,60.605082,0.999619,0.003000,4.908365,0.491745,3124.761905,655.214389,100.0,0.0,3124.761905,655.214389,100.158730,59.330446,98.079365,59.017431,120.191190,32.406426,3.476190,0.613529,1.185032,0.226780,0.867667,0.127976,0.954905,0.046408,1,250.078,255,39228.0,0.0,99.992,0.0,100.015,0.0,809.255,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.524,0.0,223.451,0.0,72.380,0.0,0.753,0.0,282.843,0.0,10003140.0,0.0,100.0,0.0,10003140.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.981,0.0,/content/Images3/3.png,2
2,0.028367,0.057912,0.073998,0.080784,-0.133789,0.008512,0.534244,1,2,7.png,7,/content/Images3,1,77,4.692,0,9.558442,1.427863,100.557675,58.022388,98.103338,59.633687,10.379961,1.091819,98.870130,58.006796,96.519481,59.576560,3.402597,0.564300,3.194805,0.559196,3.806623,0.403173,3.196818,0.352550,29.220831,46.845042,0.992974,0.032896,4.416805,0.320359,2437.402597,364.105032,100.0,0.0,2437.402597,364.105032,98.961039,57.996292,96.753247,59.526521,133.450130,23.616781,2.961039,0.375951,1.209857,0.220792,0.849429,0.129524,0.946805,0.050966,1,250.308,255,39264.0,0.0,99.987,0.0,100.001,0.0,808.326,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.626,0.0,223.554,0.0,5.766,0.0,0.755,0.0,282.843,0.0,10012320.0,0.0,100.0,0.0,10012320.0,0.0,0.0,0.0,200.0,0.0,45.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.982,0.0,/content/Images3/7.png,2
3,0.035847,0.078762,0.07823,0.101485,-0.115752,0.010542,0.933894,1,2,12.png,12,/content/Images3,1,73,7.931,0,17.041096,3.365572,103.192973,59.580318,99.320973,58.524761,13.973644,1.464372,100.917808,59.675321,97.041096,58.532847,4.479452,0.704381,4.561644,0.596481,5.004767,0.371577,4.305247,0.658070,58.915521,52.090353,0.997630,0.009785,5.643945,0.432371,4345.479452,858.220987,100.0,0.0,4345.479452,858.220987,101.356164,59.638493,98.232877,58.789739,110.340836,37.859822,4.241781,0.731391,1.187945,0.188294,0.858753,0.110053,0.912808,0.037124,1,247.070,255,38756.0,0.0,99.972,0.0,100.015,0.0,819.539,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,222.178,0.0,222.100,0.0,57.708,0.0,0.725,0.0,282.843,0.0,9882780.0,0.0,100.0,0.0,9882780.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.969,0.0,/content/Images3/12.png,2
4,0.029837,0.067296,0.079054,0.095099,-0.132865,0.009721,0.822421,1,2,13.png,13,/content/Images3,1,75,8.154,0,17.053333,3.905187,104.204653,61.052503,99.000587,59.296666,14.229160,1.984575,102.000000,61.070014,96.813333,59.280282,4.386667,0.814753,4.426667,0.751413,4.821013,0.520574,4.452253,0.680855,43.175120,59.927944,0.991787,0.017878,5.727907,0.581648,4348.600000,995.822795,100.0,0.0,4348.600000,995.822795,102.240000,61.165097,97.280000,59.174896,128.810627,22.881002,4.226667,0.775858,1.102133,0.168075,0.923240,0.106540,0.941253,0.057773,1,246.846,255,38721.0,0.0,99.945,0.0,100.028,0.0,818.811,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,222.085,0.0,221.992,0.0,52.556,0.0,0.726,0.0,282.843,0.0,9873855.0,0.0,100.0,0.0,9873855.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.968,0.0,/content/Images3/13.png,2

In [35]:
print(feats_df.shape)
feats_df.head()

(27515, 113)

,Ua,Ui,Ga,Gi,Ba,Da,Di,pattern,noise,path,seed,dir,feat_bool,num_spots,Mean,Median,Area_mean,Area_std,X_mean,X_std,Y_mean,Y_std,Perim._mean,Perim._std,BX_mean,BX_std,BY_mean,BY_std,Width_mean,Width_std,Height_mean,Height_std,Major_mean,Major_std,Minor_mean,Minor_std,Angle_mean,Angle_std,Circ._mean,Circ._std,Feret_mean,Feret_std,IntDen_mean,IntDen_std,%Area_mean,%Area_std,RawIntDen_mean,RawIntDen_std,FeretX_mean,FeretX_std,FeretY_mean,FeretY_std,FeretAngle_mean,FeretAngle_std,MinFeret_mean,MinFeret_std,AR_mean,AR_std,Round_mean,Round_std,Solidity_mean,Solidity_std,num_spots_inverted,Mean_inverted,Median_inverted,Area_inverted_mean,Area_inverted_std,X_inverted_mean,X_inverted_std,Y_inverted_mean,Y_inverted_std,Perim._inverted_mean,Perim._inverted_std,BX_inverted_mean,BX_inverted_std,BY_inverted_mean,BY_inverted_std,Width_inverted_mean,Width_inverted_std,Height_inverted_mean,Height_inverted_std,Major_inverted_mean,Major_inverted_std,Minor_inverted_mean,Minor_inverted_std,Angle_inverted_mean,Angle_inverted_std,Circ._inverted_mean,Circ._inverted_std,Feret_inverted_mean,Feret_inverted_std,IntDen_inverted_mean,IntDen_inverted_std,%Area_inverted_mean,%Area_inverted_std,RawIntDen_inverted_mean,RawIntDen_inverted_std,FeretX_inverted_mean,FeretX_inverted_std,FeretY_inverted_mean,FeretY_inverted_std,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std,full_path,classifier_pred_class
0,0.025122,0.063822,0.071957,0.106327,-0.113131,0.009186,0.611871,1,2,1.png,1,/content/Images3,1,70,5.489,0,12.300000,2.548669,99.395943,58.506181,97.530229,58.913237,12.282143,1.400962,97.371429,58.453442,95.528571,58.843551,4.071429,0.723512,4.057143,0.753766,4.245571,0.439294,3.664200,0.511781,55.108900,57.413924,0.958686,0.069883,4.926700,0.412294,3136.500000,649.910626,100.0,0.0,3136.500000,649.910626,97.942857,58.572760,96.014286,58.843981,120.129000,30.775307,3.653171,0.564778,1.177686,0.183575,0.866686,0.115368,0.879486,0.067138,1,249.511,255,39139.0,0.0,99.998,0.0,100.022,0.0,811.882,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.351,0.0,223.117,0.0,38.796,0.0,0.746,0.0,282.843,0.0,9980445.0,0.0,100.0,0.0,9980445.0,0.0,0.0,0.0,200.0,0.0,45.0,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.979,0.0,/content/Images3/1.png,2
1,0.034475,0.059956,0.080798,0.10037,-0.132577,0.008852,0.854084,1,2,3.png,3,/content/Images3,1,63,4.921,0,12.253968,2.569468,101.800571,59.297600,99.451270,58.953924,11.663270,1.365051,99.968254,59.323693,97.619048,58.964458,3.666667,0.534522,3.666667,0.534522,4.237317,0.401713,3.661714,0.572434,56.049556,60.605082,0.999619,0.003000,4.908365,0.491745,3124.761905,655.214389,100.0,0.0,3124.761905,655.214389,100.158730,59.330446,98.079365,59.017431,120.191190,32.406426,3.476190,0.613529,1.185032,0.226780,0.867667,0.127976,0.954905,0.046408,1,250.078,255,39228.0,0.0,99.992,0.0,100.015,0.0,809.255,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.524,0.0,223.451,0.0,72.380,0.0,0.753,0.0,282.843,0.0,10003140.0,0.0,100.0,0.0,10003140.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.981,0.0,/content/Images3/3.png,2
2,0.028367,0.057912,0.073998,0.080784,-0.133789,0.008512,0.534244,1,2,7.png,7,/content/Images3,1,77,4.692,0,9.558442,1.427863,100.557675,58.022388,98.103338,59.633687,10.379961,1.091819,98.870130,58.006796,96.519481,59.576560,3.402597,0.564300,3.194805,0.559196,3.806623,0.403173,3.196818,0.352550,29.220831,46.845042,0.992974,0.032896,4.416805,0.320359,2437.402597,364.105032,100.0,0.0,2437.402597,364.105032,98.961039,57.996292,96.753247,59.526521,133.450130,23.616781,2.961039,0.375951,1.209857,0.220792,0.849429,0.129524,0.946805,0.050966,1,250.308,255,39264.0,0.0,99.987,0.0,100.001,0.0,808.326,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,223.626,0.0,223.554,0.0,5.766,0.0,0.755,0.0,282.843,0.0,10012320.0,0.0,100.0,0.0,10012320.0,0.0,0.0,0.0,200.0,0.0,45.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.982,0.0,/content/Images3/7.png,2
3,0.035847,0.078762,0.07823,0.101485,-0.115752,0.010542,0.933894,1,2,12.png,12,/content/Images3,1,73,7.931,0,17.041096,3.365572,103.192973,59.580318,99.320973,58.524761,13.973644,1.464372,100.917808,59.675321,97.041096,58.532847,4.479452,0.704381,4.561644,0.596481,5.004767,0.371577,4.305247,0.658070,58.915521,52.090353,0.997630,0.009785,5.643945,0.432371,4345.479452,858.220987,100.0,0.0,4345.479452,858.220987,101.356164,59.638493,98.232877,58.789739,110.340836,37.859822,4.241781,0.731391,1.187945,0.188294,0.858753,0.110053,0.912808,0.037124,1,247.070,255,38756.0,0.0,99.972,0.0,100.015,0.0,819.539,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,222.178,0.0,222.100,0.0,57.708,0.0,0.725,0.0,282.843,0.0,9882780.0,0.0,100.0,0.0,9882780.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.969,0.0,/content/Images3/12.png,2
4,0.029837,0.067296,0.079054,0.095099,-0.132865,0.009721,0.822421,1,2,13.png,13,/content/Images3,1,75,8.154,0,17.053333,3.905187,104.204653,61.052503,99.000587,59.296666,14.229160,1.984575,102.000000,61.070014,96.813333,59.280282,4.386667,0.814753,4.426667,0.751413,4.821013,0.520574,4.452253,0.680855,43.175120,59.927944,0.991787,0.017878,5.727907,0.581648,4348.600000,995.822795,100.0,0.0,4348.600000,995.822795,102.240000,61.165097,97.280000,59.174896,128.810627,22.881002,4.226667,0.775858,1.102133,0.168075,0.923240,0.106540,0.941253,0.057773,1,246.846,255,38721.0,0.0,99.945,0.0,100.028,0.0,818.811,0.0,0.0,0.0,0.0,0.0,200.0,0.0,200.0,0.0,222.085,0.0,221.992,0.0,52.556,0.0,0.726,0.0,282.843,0.0,9873855.0,0.0,100.0,0.0,9873855.0,0.0,0.0,0.0,0.0,0.0,135.0,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.968,0.0,/content/Images3/13.png,2

In [36]:
print(feats_df.columns[13:111])

Index(['num_spots', 'Mean', 'Median', 'Area_mean', 'Area_std', 'X_mean',
       'X_std', 'Y_mean', 'Y_std', 'Perim._mean', 'Perim._std', 'BX_mean',
       'BX_std', 'BY_mean', 'BY_std', 'Width_mean', 'Width_std', 'Height_mean',
       'Height_std', 'Major_mean', 'Major_std', 'Minor_mean', 'Minor_std',
       'Angle_mean', 'Angle_std', 'Circ._mean', 'Circ._std', 'Feret_mean',
       'Feret_std', 'IntDen_mean', 'IntDen_std', '%Area_mean', '%Area_std',
       'RawIntDen_mean', 'RawIntDen_std', 'FeretX_mean', 'FeretX_std',
       'FeretY_mean', 'FeretY_std', 'FeretAngle_mean', 'FeretAngle_std',
       'MinFeret_mean', 'MinFeret_std', 'AR_mean', 'AR_std', 'Round_mean',
       'Round_std', 'Solidity_mean', 'Solidity_std', 'num_spots_inverted',
       'Mean_inverted', 'Median_inverted', 'Area_inverted_mean',
       'Area_inverted_std', 'X_inverted_mean', 'X_inverted_std',
       'Y_inverted_mean', 'Y_inverted_std', 'Perim._inverted_mean',
       'Perim._inverted_std', 'BX_inverted_mean', 'BX_inverted_std',
       'BY_inverted_mean', 'BY_inverted_std', 'Width_inverted_mean',
       'Width_inverted_std', 'Height_inverted_mean', 'Height_inverted_std',
       'Major_inverted_mean', 'Major_inverted_std', 'Minor_inverted_mean',
       'Minor_inverted_std', 'Angle_inverted_mean', 'Angle_inverted_std',
       'Circ._inverted_mean', 'Circ._inverted_std', 'Feret_inverted_mean',
       'Feret_inverted_std', 'IntDen_inverted_mean', 'IntDen_inverted_std',
       '%Area_inverted_mean', '%Area_inverted_std', 'RawIntDen_inverted_mean',
       'RawIntDen_inverted_std', 'FeretX_inverted_mean', 'FeretX_inverted_std',
       'FeretY_inverted_mean', 'FeretY_inverted_std',
       'FeretAngle_inverted_mean', 'FeretAngle_inverted_std',
       'MinFeret_inverted_mean', 'MinFeret_inverted_std', 'AR_inverted_mean',
       'AR_inverted_std', 'Round_inverted_mean', 'Round_inverted_std',
       'Solidity_inverted_mean', 'Solidity_inverted_std'],
      dtype='object')

XGBOOST

In [37]:
#! pip install xgboost
#! pip install openpyxl
#! pip install tensorflow
#! pip install graphviz
#! pip install hyperopt

from sklearn.multioutput import MultiOutputRegressor
from sklearn.svm import SVR
import numpy as np
from sklearn.model_selection import RepeatedKFold
from numpy import absolute
from pandas import read_csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from xgboost import XGBRegressor
import openpyxl
from xgboost import cv
from PIL import Image
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import operator
# for loading/processing the images
import tensorflow
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from keras.applications.vgg16 import preprocess_input

# models
from keras.applications.vgg16 import VGG16
from keras.models import Model

# clustering and dimension reduction
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import pickle
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree
import graphviz
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from hyperopt import fmin, tpe, hp,STATUS_OK
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

print("All dependencies present")

All dependencies present

In [39]:
# scale data 
# uses Standard Scaler, range [-1, 1]

## X (independent variable) --> the feature values themselves
X = feats_df[feats_df.columns[13:111]].astype(float)

## Y (dependent variables) --> the parameter values of Negan and RTO themselves
y = feats_df[["Ua","Ui","Ga","Gi","Da","Di","Ba"]].astype(float)

#Scale data with standardscaler
scaling = StandardScaler()

# Use fit and transform method
scaling.fit(X)
X_scaled = scaling.transform(X)

# select 20 percent for testing
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42) #create training split

In [40]:
print(X_test)
#print(y_train)

[[-0.33573772 -0.89290703 -0.79679244 ... -0.27982889  0.28731207
  -0.24394859]
 [-0.56983029  0.9038021   1.25503199 ...  4.04241354 -0.40972916
   3.12418153]
 [-0.63225498 -0.9682853  -0.79679244 ... -0.27982889  0.5618212
  -0.24394859]
 ...
 [-0.61664881  1.31238128  1.25503199 ... -0.27982889  0.5618212
  -0.24394859]
 [-0.63225498 -0.9682853  -0.79679244 ... -0.27982889  0.5618212
  -0.24394859]
 [-0.61664881  1.31238128  1.25503199 ... -0.27982889  0.5618212
  -0.24394859]]

In [41]:
y_test

             Ua        Ui        Ga        Gi        Da        Di        Ba
6706   0.046849  0.013064  0.115779  0.033348  0.011170  0.616537 -0.118356
19387  0.022846  0.156399  0.118046  0.069050  0.009939  1.052442 -0.193037
14847  0.045896  0.199486  0.061461  0.078881  0.009406  0.433193 -0.097045
24306  0.024930  0.051862  0.094625  0.024345  0.010236  0.498789 -0.098016
7172   0.030000  0.070000  0.080000  0.100000  0.010000  0.827444 -0.120000
...         ...       ...       ...       ...       ...       ...       ...
12968  0.014529  0.138111  0.112518  0.063431  0.010815  1.113066 -0.100108
1891   0.009662  0.195854  0.053540  0.101883  0.011343  1.117866 -0.109434
23541  0.045216  0.168554  0.076138  0.056090  0.011093  0.641815 -0.057450
16741  0.020215  0.142634  0.059699  0.142708  0.010567  0.614994 -0.108160
6244   0.013750  0.135019  0.058449  0.068174  0.008430  0.526633 -0.093800

[5503 rows x 7 columns]

In [42]:
model = xgb.XGBRegressor(n_estimators=1000, max_depth=10, eta=0.1, subsample=0.7, colsample_bytree=0.8, num_boost_round=50, objective= "reg:squarederror", device = "cuda")
model.fit(X_train, y_train)

/Users/mikhailblinov/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [14:08:54] WARNING: /Users/runner/work/xgboost/xgboost/src/context.cc:196: XGBoost is not compiled with CUDA support.
  warnings.warn(smsg, UserWarning)
/Users/mikhailblinov/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [14:08:54] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740:
Parameters: { "num_boost_round" } are not used.

  warnings.warn(smsg, UserWarning)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eta=0.1, eval_metric=None,
             feature_types=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=None, num_boost_round=50, ...)

In [43]:
## Save XGBoost Model to File
model.save_model(file_out)

/Users/mikhailblinov/Library/Python/3.9/lib/python/site-packages/xgboost/core.py:158: UserWarning: [14:09:23] WARNING: /Users/runner/work/xgboost/xgboost/src/c_api/c_api.cc:1374: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  warnings.warn(smsg, UserWarning)

In [44]:
loaded_model = xgb.XGBRegressor()

loaded_model.load_model(file_out)

#loaded_model.fit(X_train, y_train)

# make predictions
y_pred = loaded_model.predict(X_test)

pd.DataFrame(data=y_pred) 

# Columns - parameters 1-7
# Rows - Subsample of rows

print("Model loaded")

Model loaded

In [45]:
# GOAL: To determine the error rate in predicting the value of continuous, parameter data

# Converts test Y values to numpy array
true_vals = np.array(y_test)

# Outputs amount of true values
print(true_vals.shape)

# Outputs amount of predicted values
print(y_pred.shape)

# Sets counters for correct, incorrect, errors numpy array
correct = 0
incorrect = 0
p_errs = np.zeros(7)

# loops through each row in the true_vals array
for i in range(true_vals.shape[0]):
  # predicted value = predicted value from loop
  pred = y_pred[i]
  # true value = true value from loop
  true_val = true_vals[i]
  # Adds to error: absolute percent difference between true and predicted values
  p_errs += (np.abs((pred-true_val)/true_val))

# Outputs error percentages
print((p_errs/true_vals.shape[0])*100)

(5503, 7)
(5503, 7)
[32.87151772 58.13106727 26.3401836  41.73659681  8.92654801 38.65788645
 33.91673308]

In [ ]:
# select features of real images

#new_df = pd.read_pickle("data/real_df_xgboost2.pkl")
#new_feats = new_df[new_df.columns[3:111]]

new_df = pd.read_pickle("./data/Images_Classified_np126.pkl")
new_feats = new_df[new_df.columns[13:111]]

print(new_feats.head())

y_pred = None

loaded_model = xgb.XGBRegressor()

loaded_model.load_model(file_out)


#scale data
scaling=StandardScaler()

# Use fit and transform method
scaling.fit(new_feats)
new_feats_scaled = scaling.transform(new_feats)
print(new_feats_scaled.shape)

# predict params of images from real feats
y_pred = loaded_model.predict(new_feats_scaled)
print(y_pred[2])

new_df["pred_params"] = list(y_pred)

   num_spots   Mean  Median  Area_mean  Area_std      X_mean      X_std  \
0         70  5.489       0  12.300000  2.548669   99.395943  58.506181
1         63  4.921       0  12.253968  2.569468  101.800571  59.297600
2         77  4.692       0   9.558442  1.427863  100.557675  58.022388
3         73  7.931       0  17.041096  3.365572  103.192973  59.580318
4         75  8.154       0  17.053333  3.905187  104.204653  61.052503

      Y_mean      Y_std  Perim._mean  Perim._std     BX_mean     BX_std  \
0  97.530229  58.913237    12.282143    1.400962   97.371429  58.453442
1  99.451270  58.953924    11.663270    1.365051   99.968254  59.323693
2  98.103338  59.633687    10.379961    1.091819   98.870130  58.006796
3  99.320973  58.524761    13.973644    1.464372  100.917808  59.675321
4  99.000587  59.296666    14.229160    1.984575  102.000000  61.070014

     BY_mean     BY_std  Width_mean  Width_std  Height_mean  Height_std  \
0  95.528571  58.843551    4.071429   0.723512     4.057143    0.753766
1  97.619048  58.964458    3.666667   0.534522     3.666667    0.534522
2  96.519481  59.576560    3.402597   0.564300     3.194805    0.559196
3  97.041096  58.532847    4.479452   0.704381     4.561644    0.596481
4  96.813333  59.280282    4.386667   0.814753     4.426667    0.751413

   Major_mean  Major_std  Minor_mean  Minor_std  Angle_mean  Angle_std  \
0    4.245571   0.439294    3.664200   0.511781   55.108900  57.413924
1    4.237317   0.401713    3.661714   0.572434   56.049556  60.605082
2    3.806623   0.403173    3.196818   0.352550   29.220831  46.845042
3    5.004767   0.371577    4.305247   0.658070   58.915521  52.090353
4    4.821013   0.520574    4.452253   0.680855   43.175120  59.927944

   Circ._mean  Circ._std  Feret_mean  Feret_std  IntDen_mean  IntDen_std  \
0    0.958686   0.069883    4.926700   0.412294  3136.500000  649.910626
1    0.999619   0.003000    4.908365   0.491745  3124.761905  655.214389
2    0.992974   0.032896    4.416805   0.320359  2437.402597  364.105032
3    0.997630   0.009785    5.643945   0.432371  4345.479452  858.220987
4    0.991787   0.017878    5.727907   0.581648  4348.600000  995.822795

   %Area_mean  %Area_std  RawIntDen_mean  RawIntDen_std  FeretX_mean  \
0       100.0        0.0     3136.500000     649.910626    97.942857
1       100.0        0.0     3124.761905     655.214389   100.158730
2       100.0        0.0     2437.402597     364.105032    98.961039
3       100.0        0.0     4345.479452     858.220987   101.356164
4       100.0        0.0     4348.600000     995.822795   102.240000

   FeretX_std  FeretY_mean  FeretY_std  FeretAngle_mean  FeretAngle_std  \
0   58.572760    96.014286   58.843981       120.129000       30.775307
1   59.330446    98.079365   59.017431       120.191190       32.406426
2   57.996292    96.753247   59.526521       133.450130       23.616781
3   59.638493    98.232877   58.789739       110.340836       37.859822
4   61.165097    97.280000   59.174896       128.810627       22.881002

   MinFeret_mean  MinFeret_std   AR_mean    AR_std  Round_mean  Round_std  \
0       3.653171      0.564778  1.177686  0.183575    0.866686   0.115368
1       3.476190      0.613529  1.185032  0.226780    0.867667   0.127976
2       2.961039      0.375951  1.209857  0.220792    0.849429   0.129524
3       4.241781      0.731391  1.187945  0.188294    0.858753   0.110053
4       4.226667      0.775858  1.102133  0.168075    0.923240   0.106540

   Solidity_mean  Solidity_std  num_spots_inverted  Mean_inverted  \
0       0.879486      0.067138                   1        249.511
1       0.954905      0.046408                   1        250.078
2       0.946805      0.050966                   1        250.308
3       0.912808      0.037124                   1        247.070
4       0.941253      0.057773                   1        246.846

   Median_inverted  Area_inverted_mean  Area_inverted_std  X_inverted_mean  \
0              255             39139.0                0.0           99.998
1              255             39228.0                0.0           99.992
2              255             39264.0                0.0           99.987
3              255             38756.0                0.0           99.972
4              255             38721.0                0.0           99.945

   X_inverted_std  Y_inverted_mean  Y_inverted_std  Perim._inverted_mean  \
0             0.0          100.022             0.0               811.882
1             0.0          100.015             0.0               809.255
2             0.0          100.001             0.0               808.326
3             0.0          100.015             0.0               819.539
4             0.0          100.028             0.0               818.811

   Perim._inverted_std  BX_inverted_mean  BX_inverted_std  BY_inverted_mean  \
0                  0.0               0.0              0.0               0.0
1                  0.0               0.0              0.0               0.0
2                  0.0               0.0              0.0               0.0
3                  0.0               0.0              0.0               0.0
4                  0.0               0.0              0.0               0.0

   BY_inverted_std  Width_inverted_mean  Width_inverted_std  \
0              0.0                200.0                 0.0
1              0.0                200.0                 0.0
2              0.0                200.0                 0.0
3              0.0                200.0                 0.0
4              0.0                200.0                 0.0

   Height_inverted_mean  Height_inverted_std  Major_inverted_mean  \
0                 200.0                  0.0              223.351
1                 200.0                  0.0              223.524
2                 200.0                  0.0              223.626
3                 200.0                  0.0              222.178
4                 200.0                  0.0              222.085

   Major_inverted_std  Minor_inverted_mean  Minor_inverted_std  \
0                 0.0              223.117                 0.0
1                 0.0              223.451                 0.0
2                 0.0              223.554                 0.0
3                 0.0              222.100                 0.0
4                 0.0              221.992                 0.0

   Angle_inverted_mean  Angle_inverted_std  Circ._inverted_mean  \
0               38.796                 0.0                0.746
1               72.380                 0.0                0.753
2                5.766                 0.0                0.755
3               57.708                 0.0                0.725
4               52.556                 0.0                0.726

   Circ._inverted_std  Feret_inverted_mean  Feret_inverted_std  \
0                 0.0              282.843                 0.0
1                 0.0              282.843                 0.0
2                 0.0              282.843                 0.0
3                 0.0              282.843                 0.0
4                 0.0              282.843                 0.0

   IntDen_inverted_mean  IntDen_inverted_std  %Area_inverted_mean  \
0             9980445.0                  0.0                100.0
1            10003140.0                  0.0                100.0
2            10012320.0                  0.0                100.0
3             9882780.0                  0.0                100.0
4             9873855.0                  0.0                100.0

   %Area_inverted_std  RawIntDen_inverted_mean  RawIntDen_inverted_std  \
0                 0.0                9980445.0                     0.0
1                 0.0               10003140.0                     0.0
2                 0.0               10012320.0                     0.0
3                 0.0                9882780.0                     0.0
4                 0.0                9873855.0                     0.0

   FeretX_inverted_mean  FeretX_inverted_std  FeretY_inverted_mean  \
0                   0.0                  0.0                 200.0
1                   0.0                  0.0                   0.0
2                   0.0                  0.0                 200.0
3                   0.0                  0.0                   0.0
4                   0.0                  0.0                   0.0

   FeretY_inverted_std  FeretAngle_inverted_mean  FeretAngle_inverted_std  \
0                  0.0                      45.0                      0.0
1                  0.0                     135.0                      0.0
2                  0.0                      45.0                      0.0
3                  0.0                     135.0                      0.0
4                  0.0                     135.0                      0.0

   MinFeret_inverted_mean  MinFeret_inverted_std  AR_inverted_mean  \
0                   200.0                    0.0             1.001
1                   200.0                    0.0             1.000
2                   200.0                    0.0             1.000
3                   200.0                    0.0             1.000
4                   200.0                    0.0             1.000

   AR_inverted_std  Round_inverted_mean  Round_inverted_std  \
0              0.0                0.999                 0.0
1              0.0                1.000                 0.0
2              0.0                1.000                 0.0
3              0.0                1.000                 0.0
4              0.0                1.000                 0.0

   Solidity_inverted_mean  Solidity_inverted_std
0                   0.979                    0.0
1                   0.981                    0.0
2                   0.982                    0.0
3                   0.969                    0.0
4                   0.968                    0.0
(27515, 98)
[ 0.02888181  0.05787217  0.07419606  0.08122779  0.00906289  0.5339657
 -0.13312519]

In [ ]:
new_df

In [64]:
## TODO: Grab dataframe at the top (w/ all the features), drop all unnessesary columns (diff. from real_df, drop parameters)
## choose first five images and run it and see how close they are. 

print ("Ua","Ui","Ga","Gi","Da","Di","Ba")
for i in range(new_df.shape[0]):
  print(new_df["path"][i])
  print(new_df["pred_params"][i])
  print(new_df["Ua"][i], new_df["Ui"][i],new_df["Ga"][i], new_df["Gi"][i],new_df["Da"][i], new_df["Di"][i],new_df["Ba"][i]
      )

Ua Ui Ga Gi Da Di Ba
1.png
[ 0.02490418  0.0640335   0.07262938  0.10606965  0.0097551   0.61184
 -0.11362164]
0.02512223660069473 0.06382166631976507 0.07195706357833266 0.10632739510186466 0.009185636723970254 0.6118714917866803 -0.11313134072543651
3.png
[ 0.03404492  0.06016414  0.08108194  0.1010063   0.00927781  0.8539903
 -0.1320489 ]
0.03447465809161778 0.0599556426453826 0.0807983471177822 0.10037032303039066 0.008852352175844071 0.8540837792143913 -0.13257673761191435
7.png
[ 0.02888181  0.05787217  0.07419606  0.08122779  0.00906289  0.5339657
 -0.13312519]
0.028366614907530105 0.057912397008865274 0.07399764894945274 0.08078401006827379 0.008512024948034682 0.5342443632295809 -0.1337886113318717
12.png
[ 0.03620365  0.06268869  0.07712788  0.09331793  0.01043348  0.90076303
 -0.11233992]
0.035846536188983404 0.07876223021258162 0.07822983359535865 0.10148492077956844 0.010542271530694876 0.9338941354749168 -0.11575188943822867
13.png
[ 0.02987736  0.06755836  0.07887999  0.09516858  0.00986277  0.82252634
 -0.13255268]
0.029836938471012774 0.0672959832190558 0.07905404165311744 0.09509871804430664 0.009720961053018685 0.8224214377688012 -0.13286469707005166
14.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.03261109289668942 0.06647805415242507 0.07132365162643975 0.09420651090617359 0.008920605677632726 0.6379695542803083 -0.13739565290756434
15.png
[ 0.02687074  0.08207727  0.0855208   0.11077681  0.00986439  0.8645108
 -0.1249812 ]
0.0237786590252706 0.07952941738108492 0.075065171860497 0.08444112939751015 0.008201310020545565 0.8825725752084843 -0.12491341942888594
17.png
[ 0.02497924  0.13999186  0.12507565  0.08791871  0.00999774  0.8658875
 -0.10090952]
0.019284879523139464 0.1058369532946387 0.15752361448757118 0.04695369289292795 0.00811242477452445 0.5035623879273112 -0.13293962245949356
18.png
[ 0.02575361  0.06779496  0.07881608  0.11789741  0.00899159  0.6157737
 -0.13316654]
0.025636850863694164 0.06777666580474002 0.07865124111337393 0.117787684719385 0.008537976629514145 0.6156950602318888 -0.13300687493979763
21.png
[ 0.03114218  0.04923334  0.07921463  0.08385364  0.0107184   0.974714
 -0.11350293]
0.03131457804147111 0.0489524564821156 0.07919825102012003 0.08358633836740204 0.01086248344721976 0.9745743751464844 -0.11339447729848791
23.png
[ 0.0333447   0.091809    0.07090192  0.09309372  0.00935477  0.7027363
 -0.126111  ]
0.033381861797285375 0.09208991619759593 0.07070756511898502 0.09373135951208043 0.008255698392269657 0.7032098536316457 -0.1262215431727156
24.png
[ 0.03222735  0.05976852  0.08240008  0.0993377   0.00925252  0.688939
 -0.1089789 ]
0.031845121582304216 0.05921683874225603 0.08255025574487752 0.10006190394162205 0.008370232816991499 0.6881558141419784 -0.1086602612280303
26.png
[ 0.0365752   0.07932024  0.08858433  0.1055999   0.00980302  0.5049568
 -0.11400276]
0.03680290737852648 0.07888336004263852 0.089255656955326 0.10614694138248572 0.009926500232406104 0.5048012189089556 -0.11313755285967445
27.png
[ 0.03289457  0.07569068  0.08545282  0.11592402  0.01019589  0.6052588
 -0.11244382]
0.03273323704072302 0.07626540580777014 0.08561344357172307 0.11648408860060105 0.010743378883617696 0.6055694086681223 -0.11271409568351115
28.png
[ 0.02803102  0.07032146  0.07974064  0.0939927   0.01060974  0.78486687
 -0.11923785]
0.028547738944119706 0.06991009933963901 0.08047671551764835 0.09378261721170379 0.010715593635062207 0.7855357940398456 -0.11954623614555483
31.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.03581325806122891 0.06390881834209962 0.07211726354359947 0.08100249098655109 0.010640619041747885 0.7046521276375727 -0.12644704851368163
32.png
[ 0.02647191  0.07481579  0.08813504  0.10592436  0.00860355  0.5765925
 -0.10993972]
0.026599624743777653 0.07491503256000355 0.08804090795700976 0.10628773891980103 0.008134111919623661 0.5763652956838697 -0.10976096494429362
36.png
[ 0.02845516  0.07383309  0.08064262  0.10931187  0.00970399  0.7166581
 -0.13427107]
0.02728387955099462 0.07081258005662334 0.07668593515930032 0.09839164209587932 0.008193657821973642 0.7419253688782094 -0.13313228675705527
37.png
[ 0.02576097  0.04605572  0.07622399  0.09201895  0.01057953  0.88122684
 -0.12739193]
0.02561212971881417 0.04537599424328456 0.07648717267608082 0.09216735169704365 0.010566860674003281 0.8813262078795627 -0.12744106958046797
38.png
[ 0.02988382  0.07090157  0.07159201  0.0939162   0.0108228   0.7326035
 -0.12028433]
0.029346663278645466 0.07125401822792343 0.07032631877156503 0.09350171397526316 0.010788488130488359 0.7319993153042269 -0.12062373266917266
39.png
[ 0.03172267  0.05096469  0.07412371  0.08308298  0.0105715   0.9084712
 -0.1136549 ]
0.032017568297105926 0.050452586533022474 0.07374377592497937 0.08268942086461185 0.010425022306463855 0.908457833491241 -0.11371200103943778
40.png
[ 0.03650191  0.06634942  0.08091015  0.10567401  0.00964354  0.9343753
 -0.11132091]
0.03675271225236184 0.06668795327146142 0.08084311820827347 0.10656829142124137 0.009602914187103486 0.9348850440850063 -0.11068331833845027
42.png
[ 0.03376051  0.05877103  0.08826756  0.1192897   0.00999221  0.8487892
 -0.12493787]
0.033633487427394214 0.05904001339272073 0.08865670307703565 0.11963733251785946 0.010122262745499365 0.8491835940337649 -0.12471640262681616
43.png
[ 0.03478206  0.06018778  0.08828175  0.11874456  0.00911855  0.81125516
 -0.12876008]
0.03469538743936934 0.060304603433755974 0.08862454840713775 0.11887847854390153 0.008810626183957226 0.8111263347852706 -0.12847794721162098
44.png
[ 0.0305503   0.07264799  0.0729248   0.09370429  0.00891897  0.7940791
 -0.13720593]
0.030249937275810584 0.07369986176909733 0.07151013513380627 0.09336179326943544 0.008107657074270545 0.7946124579559755 -0.13798102636887027
45.png
[ 0.02503566  0.0736775   0.08050107  0.08531549  0.00921846  0.61280763
 -0.13034944]
0.024946081139376686 0.07252520150017773 0.08079494516269921 0.08554481975729664 0.00831750596266894 0.6131716093357635 -0.12989841286263873
46.png
[ 0.02492576  0.06329186  0.07326256  0.10636961  0.01011029  0.5064106
 -0.11199547]
0.02438167154186406 0.06265370805157934 0.0730705104412936 0.10670803099378535 0.010416667654361762 0.5067603063903796 -0.11213501457317751
47.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.030560494326580614 0.08412889393803417 0.07023797298620482 0.09673496401549292 0.01093432631654853 0.5337289519558155 -0.11240442923201212
51.png
[ 0.0347807   0.09071381  0.08704011  0.11740967  0.00883627  0.9783135
 -0.13094904]
0.03526247195845194 0.09187959498797565 0.0867367791020167 0.11803339214161325 0.008471235069568593 0.9784622130241608 -0.1310176677450732
52.png
[ 0.02974002  0.09516934  0.07938356  0.0863931   0.00960437  0.8254023
 -0.11934125]
0.029441985900905486 0.08298879010766758 0.08177688380472167 0.09308305206356772 0.009229331327559744 0.8459948211075785 -0.11339449349100429
54.png
[ 0.02955839  0.08596526  0.08289225  0.09363151  0.01005742  0.94196284
 -0.14240955]
0.02301671282155795 0.08858623213321135 0.08201458759921354 0.09617218331087793 0.009098259275565429 0.6641334299568596 -0.11779495946849869
55.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.0290782729136846 0.04919415138634255 0.07102917107759425 0.08124702492660985 0.010045302807047995 0.6608888811537537 -0.13695338128690782
57.png
[ 0.02503885  0.08278561  0.07926034  0.11281211  0.01117237  0.63225627
 -0.12544674]
0.024479851871960216 0.08292205519286935 0.07942017456388176 0.11334300454560149 0.011606017541236979 0.6313884845147686 -0.12596082922463853
61.png
[ 0.02754748  0.05920712  0.07622909  0.0892122   0.00928923  0.6744593
 -0.1049212 ]
0.02763740620802717 0.05899821978136159 0.07576910451529333 0.08942335139643762 0.00857787284739528 0.6747483160934096 -0.10379034286974477
62.png
[ 0.03133188  0.10473374  0.08523923  0.09950164  0.01057081  0.7296937
 -0.11636708]
0.028641472087992885 0.08620843557561411 0.08980174088207551 0.09280582873836614 0.01011345160750412 0.818999837064556 -0.10742605676787587
63.png
[ 0.02704489  0.0720195   0.07584944  0.09815268  0.01047031  0.81191057
 -0.13310471]
0.02618937376742112 0.05482337291840673 0.07429534413055236 0.08135205942021731 0.011218413642047991 0.7126977435657258 -0.12464630635699897
66.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.033790226634896336 0.07906663430273092 0.08182697009331365 0.11374933929406059 0.011670511914784597 0.5261680098261283 -0.12477873929661179
67.png
[ 0.02622383  0.0835889   0.0882719   0.11860027  0.01050732  0.9742255
 -0.11239631]
0.026273120451613445 0.08348388229806802 0.08858943558443039 0.11862104163420072 0.011105660109736362 0.9734592787278781 -0.11209747417953894
68.png
[ 0.03191796  0.09155149  0.08794996  0.09251176  0.00996097  0.8740517
 -0.11868212]
0.031752653657332056 0.09159130375317222 0.08771758216097526 0.09266780530530229 0.010307106535636802 0.8743184209322612 -0.11886675552498532
70.png
[ 0.03302227  0.09064899  0.08621952  0.09380001  0.00903394  0.59881765
 -0.13195303]
0.03307836811811 0.09015749570615633 0.08640437524239705 0.09349895916824084 0.008713720966487776 0.5986434274252768 -0.13186942108900107
71.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.03617959284536884 0.0798341495727723 0.07084749133936966 0.09981667197267323 0.009961209571476658 0.5139070822427165 -0.12330464407943349
72.png
[ 0.02785721  0.0804924   0.07730378  0.10622392  0.01099313  0.9334863
 -0.1366325 ]
0.02785906558738742 0.0806129222571249 0.07800897308830668 0.10615321771462752 0.011355931059995876 0.9333796959065109 -0.1368981852491093
79.png
[ 0.03289682  0.06633984  0.0722013   0.08165529  0.00918281  0.70708066
 -0.12208159]
0.032741221990755597 0.06611042218639555 0.07184679072901176 0.08151727653669093 0.008852882144376933 0.7071455193121361 -0.12194367913789365
80.png
[ 0.03490801  0.0479671   0.07316271  0.10768615  0.00974814  0.8881106
 -0.10857939]
0.03537196134865796 0.04819238353604231 0.07318727366404389 0.1076754768953769 0.009809067447651055 0.8883192339535494 -0.10825894381342094
81.png
[ 0.02935812  0.06069553  0.08261494  0.11296826  0.0092049   0.75508815
 -0.12020914]
0.029043884487370684 0.07183651945387022 0.08204730366105932 0.1108860487892343 0.0093447300425929 0.8391174720370043 -0.1347916129598885
82.png
[ 0.02737722  0.09431762  0.07473079  0.10490008  0.010071    0.6961828
 -0.11905603]
0.02710519480378537 0.09498705538248903 0.07422920557163133 0.1050189147792203 0.010164034334990996 0.6952253272061448 -0.11874156075280333
83.png
[ 0.02782695  0.06671876  0.07658105  0.08067042  0.01023574  0.7836394
 -0.11191961]
0.02763515109728184 0.07022908942112403 0.08854209481432987 0.09863619725563723 0.010971020073631517 0.8189962577146221 -0.1039222795474879
84.png
[ 0.03041618  0.04802159  0.0801921   0.0923124   0.01070303  0.6351355
 -0.10727345]
0.030216325924718172 0.04791798722004307 0.08068287353702783 0.09239358057888761 0.01170508471939615 0.634788691477471 -0.10630110176203687
86.png
[ 0.03320085  0.05613312  0.08883226  0.0919669   0.00908001  0.61320823
 -0.1187128 ]
0.03325788111274544 0.05622895926426441 0.0893614401393434 0.09211980952655935 0.00899499794471065 0.613162982558275 -0.1185275614044923
87.png
[ 0.0304078   0.07465605  0.07669245  0.08251426  0.00987822  0.7517039
 -0.12480842]
0.030525896954830087 0.07434150509536219 0.07663809232420654 0.08163249628299851 0.009657417107299837 0.7515463023495818 -0.12548461924362342
88.png
[ 0.02414102  0.06777944  0.07949913  0.10716362  0.01116368  0.84110546
 -0.12037555]
0.024361041139901646 0.06790419057273832 0.0806108428209928 0.10794821341823903 0.01162014330594192 0.8407770668191663 -0.1201165518390698
93.png
[ 0.02863332  0.07712375  0.07635637  0.09025764  0.01113267  0.8692001
 -0.11942815]
0.028410275659714136 0.07833544658781778 0.07668125611788713 0.09044401592754513 0.011725363759449312 0.8686051492694603 -0.1191957055543788
94.png
[ 0.03462945  0.08002912  0.07951592  0.10324145  0.00991428  0.8448696
 -0.12513573]
0.03589052886271918 0.08981333257286368 0.0851003741938447 0.0964932708499684 0.01099437390276141 0.8017530767420693 -0.13380859278821838
95.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.031984314244359324 0.05974627831738788 0.07221716917445749 0.10290276534924084 0.010188709141109455 0.6579999602982011 -0.12835763510700227
96.png
[ 0.03194117  0.09095461  0.07990259  0.09471102  0.00975577  0.62587553
 -0.12287318]
0.03395026385625479 0.09235715648374027 0.0806371792400087 0.09184837555247485 0.009506649155012698 0.5448821955260605 -0.12149086213765353
97.png
[ 0.03153914  0.08136602  0.08312617  0.11432584  0.0089053   0.60973316
 -0.11485563]
0.031193557857701358 0.08210192428774234 0.08195819539040974 0.11419936570320618 0.008596432499624393 0.6084988353503287 -0.11467758271184036
103.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.02920658906549474 0.058486672871861344 0.07287227094589988 0.11749130539307207 0.011923787378525364 0.9127682140921025 -0.13673609342178772
105.png
[ 0.02567376  0.09310933  0.08086532  0.10035821  0.00957039  0.7853773
 -0.14946425]
0.023025100258964367 0.07052110632656886 0.08453235338242786 0.10816868609941863 0.009357151922619331 0.5692514806510266 -0.11149213556095874
107.png
[ 0.03002468  0.08269095  0.08685522  0.09586705  0.0090777   0.76300174
 -0.11634365]
0.03039061803559461 0.08242823373226654 0.08688794723728763 0.09557565745714039 0.008680269931435147 0.7631323059576749 -0.11646649629688498
108.png
[ 0.02471378  0.05372813  0.07830612  0.10832258  0.00966019  0.7354157
 -0.13113338]
0.024849669050829845 0.05402148916553255 0.07805387114005226 0.1084883944402557 0.009461156393006476 0.7355627890099817 -0.13134972080306884
109.png
[ 0.03431512  0.05025201  0.07901228  0.08599145  0.01006165  0.91162926
 -0.13556355]
0.03457262116370764 0.05012873124291849 0.07883094601970843 0.08475395544408791 0.01028250861401798 0.9112036614075165 -0.13582205242503773
110.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.027931467770966507 0.08433580950477063 0.07140467645512494 0.09144459714073705 0.01108264516973021 0.5022006671527655 -0.1242053814556181
111.png
[ 0.03008163  0.091286    0.07966501  0.0819634   0.00952113  0.5614881
 -0.10753199]
0.030013477549970455 0.091056369397793 0.07921415116600225 0.08193812218367258 0.009435380238003426 0.5617455834104355 -0.10710459580892794
112.png
[ 0.03468429  0.05718404  0.08151846  0.10843068  0.00931672  0.7907059
 -0.13371564]
0.034868087682665645 0.05740486072777384 0.08219168194896026 0.10862229393692846 0.009209310468966185 0.7910943174672415 -0.13402427517545112
114.png
[ 0.03201725  0.0754301   0.08439667  0.09048547  0.01090088  0.54362184
 -0.12512006]
0.03229177531065318 0.07510741171803696 0.08477168797658756 0.0898961391587424 0.011583486153139939 0.5431742347131738 -0.1260292788868216
115.png
[ 0.0305694   0.04838109  0.08609499  0.0834209   0.01106275  0.8284826
 -0.11569859]
0.0313486463731946 0.047902426224009996 0.08654502157981377 0.08331105567578678 0.011984380518771234 0.8281950456344144 -0.11512888401934626
119.png
[ 0.02379446  0.07278033  0.07420912  0.10598873  0.01144755  0.86604565
 -0.10827421]
0.02376282926404301 0.07309450062910697 0.07412696217016006 0.10591942120648887 0.011680604335690008 0.8658801199471189 -0.10810134114446836
120.png
[ 0.02556835  0.07308838  0.08321764  0.09105778  0.00976237  0.7246027
 -0.10232777]
0.024567562176099587 0.07313230653106974 0.08322116624121496 0.09117774604442681 0.009585592203552479 0.7241927307975032 -0.10231000056630664
121.png
[ 0.0302323   0.06034484  0.07961088  0.11619275  0.0104076   0.5908945
 -0.11392554]
0.029871632963699456 0.06083520533394502 0.08037244959922607 0.11620141091077837 0.010881528256364136 0.5910989767187861 -0.11381972428092964
122.png
[ 0.03610878  0.05867295  0.08239097  0.1094906   0.00940027  0.77576995
 -0.11137605]
0.03425589225369957 0.06510101288781957 0.08784724973069605 0.10888866650973066 0.010070015801089993 0.8426878617650856 -0.13137384318977274
124.png
[ 0.0311417   0.07245887  0.07689708  0.09107201  0.00903314  0.58963466
 -0.11825464]
0.03086888074960492 0.07285736937135089 0.07703637666894236 0.09104504284832014 0.008492554220915709 0.5895832916262093 -0.11785087091230781
126.png
[ 0.02506365  0.06079546  0.08707769  0.09339486  0.00996308  0.71181697
 -0.13617863]
0.024329681292348325 0.06038753087476427 0.08754286084649812 0.09222434838013327 0.00964786367316677 0.7111662126067255 -0.13653895488522633
128.png
[ 0.0300634   0.08828044  0.08737264  0.10401203  0.00992797  0.99583644
 -0.10840802]
0.030122631063629474 0.08802172249928322 0.08770176213764112 0.10404567473917985 0.009700522987643047 0.9955205505408289 -0.10850220412273173
130.png
[ 0.02588305  0.0687987   0.07797079  0.10931218  0.01080865  0.8641763
 -0.13069144]
0.02607201827539502 0.06920377522928026 0.07780703748467048 0.10902112497221375 0.011552360151160297 0.8641312238254253 -0.13108374662772537
131.png
[ 0.02883082  0.04633761  0.07407903  0.10489765  0.00999597  0.8164904
 -0.11289609]
0.028400378939258855 0.04613789779805862 0.0740359345861824 0.10525591894847684 0.009736871556005661 0.8170196498588405 -0.11254666397791561
135.png
[ 0.02748209  0.08974515  0.08260606  0.09375101  0.00954976  0.721422
 -0.12531865]
0.025624809879362435 0.0633547903702028 0.08042653241416886 0.0829402571679991 0.008088541606426644 0.7091706170066674 -0.1289539434525827
136.png
[ 0.0333343   0.08757757  0.06417557  0.11072064  0.0100734   0.8110265
 -0.1301422 ]
0.03611219139718719 0.07048301148317171 0.07303756621359661 0.09078111756140445 0.008787974719164399 0.5630474713326944 -0.12231785992249808
137.png
[ 0.02774813  0.07569376  0.08098064  0.08260389  0.00988619  0.5024877
 -0.11521115]
0.02799357190052221 0.07570915126609894 0.08184474657408185 0.08226851798948684 0.0095784277917071 0.5024691286034408 -0.11533099512732956
138.png
[ 0.02688477  0.07676774  0.08370947  0.10886376  0.00960757  0.58718204
 -0.12880827]
0.026766000804502834 0.07736193168958377 0.08371664562542133 0.10928454991527493 0.009888828646323889 0.5885911577593839 -0.12911645487235865
140.png
[ 0.03498997  0.06739191  0.08086233  0.08239537  0.00956061  0.8959723
 -0.12897441]
0.03478905858824417 0.06693140179265153 0.08055340158252133 0.0815585170683549 0.008954254253191983 0.8957970387861911 -0.12900276131066954
141.png
[ 0.03598143  0.0860572   0.0852159   0.08513048  0.0106312   0.76419014
 -0.10447612]
0.03664555335254535 0.0866687689899594 0.08525824750328438 0.08521023680463152 0.011192572393878141 0.7641690869636028 -0.10442751043268475
146.png
[ 0.03272983  0.05731331  0.08531579  0.09038565  0.01055324  0.58770686
 -0.11771232]
0.03244522815691379 0.05699723084059911 0.08558160980935177 0.0905192153001853 0.011284217192771088 0.5874357239133773 -0.11751361609954553
147.png
[ 0.02724317  0.08927924  0.0789512   0.08229285  0.01005731  0.7920411
 -0.12393159]
0.02723399606897595 0.08979007355520287 0.07877720845698107 0.08240751151785589 0.010041072079823991 0.7923031594339977 -0.12450457351308186
148.png
[ 0.0275998   0.08447928  0.08610772  0.10970673  0.00891864  0.6487731
 -0.13015743]
0.027503088103793382 0.08472197918671302 0.08595629405869604 0.10954593742232535 0.008642033851609155 0.649123200144645 -0.13042988891677315
149.png
[ 0.02824663  0.07980863  0.07635359  0.11672793  0.01093425  0.71078134
 -0.1128704 ]
0.028263181817212657 0.08005655510560476 0.07687675482138538 0.1175571356773029 0.01152576537280438 0.7106679419222063 -0.11271924213404055
150.png