<a href="https://colab.research.google.com/github/vcellmike/PatternsFormation/blob/main/Working/2024_08_21_XGBoost_on_ImageJ_Features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import json
import os
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from sklearn.metrics import accuracy_score, classification_report
from transformers import AutoModel, AutoTokenizer, get_scheduler
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from torch.optim import AdamW
from tqdm.notebook import tqdm, trange
from time import perf_counter
from PIL import Image
import pandas as pd
#from google.colab import drive
from PIL import Image
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import pickle

print("All dependencies present.")

All dependencies present.

In [2]:
# set random seeds for repeatability
import numpy as np
import random

def set_seed(seed_val):
    random.seed(seed_val)
    np.random.seed(seed_val)
    torch.manual_seed(seed_val)
    torch.cuda.manual_seed_all(seed_val)

print("Seed set")

Seed set

In [4]:
seed_val = 42
set_seed(seed_val)

In [12]:
# !unzip "/content/drive/Shareddrives/Summer_2023_VCell_Ml/2024-05-09 New Work/Saved_variables/05-09-2024_all_images-20240509T194653Z-001.zip"
# !unzip "/content/drive/Shareddrives/Summer_2023_VCell_Ml/2024-05-09 New Work/New Image Generation/Generated Images-20240523T233205Z-001.zip"
# !unzip "/content/drive/Shareddrives/Summer_2023_VCell_Ml/2024-05-09 New Work/New Image Generation/Generated_Images_7-2-24-20240702T205017Z-001.zip"
# !unzip "/content/drive/MyDrive/2024_Summer_Work_(Shared_Drive_Is_Full)/As of 2024-08-22 Saved variables and data/Real_Images/2024-08-22_ImageJ_Data/Regular.zip"
# !unzip "/content/drive/MyDrive/2024_Summer_Work_(Shared_Drive_Is_Full)/As of 2024-08-22 Saved variables and data/Real_Images/2024-08-22_ImageJ_Data/Inverse.zip"

#!powershell -Command "Expand-Archive -Path './content/ImageJ_data/Inverse_resized.zip' -DestinationPath './content/ImageJ_data'" 

#!unzip "/content/drive/MyDrive/2024_Summer_Work_(Shared_Drive_Is_Full)/As of 2024-08-22 Saved variables and data/Real_Images/2024-08-22_ImageJ_Data/Regular_resized.zip"

#!powershell -Command "Expand-Archive -Path './content/ImageJ_data/Regular_resized.zip' -DestinationPath './content/ImageJ_data'" 

#!unzip "/content/drive/MyDrive/2024_Summer_Work_(Shared_Drive_Is_Full)/As of 2024-08-22 Saved variables and data/Real_Images/2024-08-22_ImageJ_Data/Inverse_resized.zip"
#!echo "Unzip Complete"

In [5]:
# TODO: Replace curr_df_np126.pkl with images_unclassified

with open("./data/data_old/2024-08-18_curr_df_np126.pkl", 'rb') as f:
  feats_df = pickle.load(f) # deserialize using load()

feats_df.head()
#feats_df = feats_df.drop([700,1159,4061], axis = "rows")
#feats_df.reset_index(inplace = True, drop = True)
#feats_df["class"] = np.array(feats_df["class"].astype(int) -1).astype(int)
#print(np.unique(np.array(feats_df["class"]), return_counts = True))

  class noise   path seed                dir  pred_class        pc1        pc2
0     2     2  0.png    0  /content/Images3/           1 -31.683971 -14.198348
1  None     2  1.png    1  /content/Images3/           2  31.977729 -17.444531
2     2     2  2.png    2  /content/Images3/           1 -31.683971 -14.198348
3  None     2  3.png    3  /content/Images3/           2  31.347501 -16.048195
4     2     2  4.png    4  /content/Images3/           1 -31.683971 -14.198348

In [14]:
#with open("./data/data_old/2024-08-19_feat_array_unscaled.pkl", 'rb') as f:
#  feat_array_classified = pickle.load(f) # deserialize using load()

#with open("./data/data_old/2024-08-18_curr_df_np126.pkl", 'rb') as f:
#  df_classes_classified = pickle.load(f) # deserialize using load()

#feat_array_classified

In [6]:
# Features, 33k images
with open("./data/data_old/2024-08-19_feats_df_narrow_np126.pkl", 'rb') as f:
  feats_df_new = pickle.load(f) # deserialize using load()

feats_df_new

,Ua,Ui,Ga,Gi,Ba,Da,Di,pattern,noise,path,...,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std
0,0.025122,0.063822,0.071957,0.106327,-0.113131,0.009186,0.611871,1,2,1.png,...,45.000,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.979,0.0
1,0.034475,0.059956,0.080798,0.10037,-0.132577,0.008852,0.854084,1,2,3.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.981,0.0
2,0.028367,0.057912,0.073998,0.080784,-0.133789,0.008512,0.534244,1,2,7.png,...,45.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.982,0.0
3,0.036364,0.055723,0.088968,0.107719,-0.126763,0.011323,0.809702,1,2,11.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.985,0.0
4,0.035847,0.078762,0.07823,0.101485,-0.115752,0.010542,0.933894,1,2,12.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.969,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33765,0.047659,0.179187,0.122823,0.048745,-0.080442,0.011393,0.468993,0,3,noise 3 21522.0.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
33766,0.049658,0.087822,0.124444,0.105756,-0.140723,0.008773,1.001359,1,7,noise 7 21167.0.png,...,135.288,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.920,0.0
33767,0.025269,0.096806,0.0973,0.124239,-0.046031,0.008247,0.752525,0,5,noise 5 21035.0.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
33768,0.029474,0.085933,0.103994,0.103636,-0.119675,0.008054,1.058641,1,3,noise 3 24575.0.png,...,135.000,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.795,0.0
33769,0.019996,0.117955,0.161475,0.075774,-0.063299,0.009488,0.414752,0,4,noise 4 24351.0.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0

In [7]:
feats_df_new

,Ua,Ui,Ga,Gi,Ba,Da,Di,pattern,noise,path,...,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std
0,0.025122,0.063822,0.071957,0.106327,-0.113131,0.009186,0.611871,1,2,1.png,...,45.000,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.979,0.0
1,0.034475,0.059956,0.080798,0.10037,-0.132577,0.008852,0.854084,1,2,3.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.981,0.0
2,0.028367,0.057912,0.073998,0.080784,-0.133789,0.008512,0.534244,1,2,7.png,...,45.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.982,0.0
3,0.036364,0.055723,0.088968,0.107719,-0.126763,0.011323,0.809702,1,2,11.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.985,0.0
4,0.035847,0.078762,0.07823,0.101485,-0.115752,0.010542,0.933894,1,2,12.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,0.969,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33765,0.047659,0.179187,0.122823,0.048745,-0.080442,0.011393,0.468993,0,3,noise 3 21522.0.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
33766,0.049658,0.087822,0.124444,0.105756,-0.140723,0.008773,1.001359,1,7,noise 7 21167.0.png,...,135.288,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.920,0.0
33767,0.025269,0.096806,0.0973,0.124239,-0.046031,0.008247,0.752525,0,5,noise 5 21035.0.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0
33768,0.029474,0.085933,0.103994,0.103636,-0.119675,0.008054,1.058641,1,3,noise 3 24575.0.png,...,135.000,0.0,200.0,0.0,1.001,0.0,0.999,0.0,0.795,0.0
33769,0.019996,0.117955,0.161475,0.075774,-0.063299,0.009488,0.414752,0,4,noise 4 24351.0.png,...,135.000,0.0,200.0,0.0,1.000,0.0,1.000,0.0,1.000,0.0

In [8]:
feats_df.head()

  class noise   path seed                dir  pred_class        pc1        pc2
0     2     2  0.png    0  /content/Images3/           1 -31.683971 -14.198348
1  None     2  1.png    1  /content/Images3/           2  31.977729 -17.444531
2     2     2  2.png    2  /content/Images3/           1 -31.683971 -14.198348
3  None     2  3.png    3  /content/Images3/           2  31.347501 -16.048195
4     2     2  4.png    4  /content/Images3/           1 -31.683971 -14.198348

In [9]:
# Sets pred-class column equal to class column
feats_df["pred_class"] = feats_df["class"]

In [10]:
# two dataframes 
# Possibly df1 = feats_df_new
df1 = feats_df[["noise","path","seed","dir","pred_class"]]
df2 = feats_df[["noise","path","seed","dir","pred_class"]]

# concat's predicted and manual classified dataframes (df_classes_classified + feats_df)
pred_and_manual_df = pd.concat([df1, df2], axis=0)

pred_and_manual_df.reset_index(inplace = True, drop = True)
feats_df_new.reset_index(inplace = True, drop = True)

pred_and_manual_df.tail(20)

      noise                 path     seed                dir pred_class
64400     4  noise 4 22201.0.png  22201.0  /content/Images1/       None
64401     3  noise 3 24788.0.png  24788.0  /content/Images1/          1
64402     5  noise 5 24550.0.png  24550.0  /content/Images1/          1
64403     3  noise 3 23212.0.png  23212.0  /content/Images1/       None
64404     4  noise 4 20924.0.png  20924.0  /content/Images1/       None
64405     6  noise 6 20401.0.png  20401.0  /content/Images1/          1
64406     3  noise 3 22691.0.png  22691.0  /content/Images1/          1
64407     6  noise 6 24543.0.png  24543.0  /content/Images1/       None
64408     6  noise 6 22123.0.png  22123.0  /content/Images1/          1
64409     5  noise 5 24768.0.png  24768.0  /content/Images1/          1
64410     5  noise 5 24343.0.png  24343.0  /content/Images1/       None
64411     4  noise 4 23267.0.png  23267.0  /content/Images1/       None
64412     5  noise 5 20825.0.png  20825.0  /content/Images1/          2
64413     6  noise 6 24944.0.png  24944.0  /content/Images1/          2
64414     3  noise 3 21511.0.png  21511.0  /content/Images1/          2
64415     4  noise 4 20872.0.png  20872.0  /content/Images1/          2
64416     4  noise 4 22801.0.png  22801.0  /content/Images1/          1
64417     5  noise 5 21620.0.png  21620.0  /content/Images1/          2
64418     3  noise 3 21522.0.png  21522.0  /content/Images1/          2
64419     7  noise 7 21167.0.png  21167.0  /content/Images1/       None

In [11]:
#add full path to each dataframe to allow matching based on unique path
# df with all params: feats_df_new
# df with predicted classes: pred_and_manual_df

fdf_full_path = []
for i in range(feats_df_new.shape[0]):
  fdf_full_path.append(feats_df_new["dir"][i] + feats_df_new["path"][i])


cdf_full_path = []
for j in range(pred_and_manual_df.shape[0]):
  cdf_full_path.append((pred_and_manual_df["dir"][j] + pred_and_manual_df["path"][j]))


feats_df_new["full_path"] = fdf_full_path
pred_and_manual_df["full_path"] = cdf_full_path

In [12]:
feats_df.head(20)

,class,noise,path,seed,dir,pred_class,pc1,pc2
0,2,2,0.png,0,/content/Images3/,2,-31.683971,-14.198348
1,None,2,1.png,1,/content/Images3/,None,31.977729,-17.444531
2,2,2,2.png,2,/content/Images3/,2,-31.683971,-14.198348
3,None,2,3.png,3,/content/Images3/,None,31.347501,-16.048195
4,2,2,4.png,4,/content/Images3/,2,-31.683971,-14.198348
5,None,2,5.png,5,/content/Images3/,None,28.932574,-14.527230
6,None,2,6.png,6,/content/Images3/,None,1.895376,-5.157169
7,None,2,7.png,7,/content/Images3/,None,32.919621,-18.103002
8,None,2,8.png,8,/content/Images3/,None,31.071663,-16.434768
9,None,2,10.png,10,/content/Images3/,None,28.874940,-14.434144
10,None,2,12.png,12,/content/Images3/,None,32.159282,-16.519775
11,None,2,13.png,13,/content/Images3/,None,31.390694,-16.460874
12,1,2,14.png,14,/content/Images3/,1,0.036469,36.126034
13,None,2,15.png,15,/content/Images3/,None,32.617910,-18.177292
14,None,2,16.png,16,/content/Images3/,None,28.231867,-14.343487
15,2,2,17.png,17,/content/Images3/,2,-31.683971,-14.198348
16,None,2,18.png,18,/content/Images3/,None,32.330986,-18.022332
17,None,2,19.png,19,/content/Images3/,None,29.918454,-16.244487
18,None,2,20.png,20,/content/Images3/,None,27.401690,-12.827250
19,None,2,21.png,21,/content/Images3/,None,30.052679,-13.782816

In [13]:
## Indices 1 - ALl elements in feats_df_new that match full paths with rows in pred_and_manual_df.


indices_1 = []
indices_2 = []
errors = 0
counter = 0
for i in range(feats_df_new.shape[0]):
  #pull up path to search for
  path = pred_and_manual_df["full_path"][i]

  #find index within feats_df that matches path
  ind_df = feats_df_new[feats_df_new["full_path"] == path]
  #print(ind_df.head())
  #print("Ind_df.shape[0] ", ind_df.shape[0])
    
  if ind_df.shape[0] == 1:
    ind = ind_df.index[0]
    # print(ind_df.head())
#    #print("ind: " + str(ind) + " i: " + str(i))
    indices_1.append(ind)
    indices_2.append(i)
  else:
   # indices.append("error")
   # print("error")
    errors += 1


  if counter % 1000 == 0:
    print(counter)
  counter += 1

#print(ind_df.head())
#print(indices_2)
print("Complete.")

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
Complete.

In [14]:
# match dfs
# drops all values of feats_df_new that aren't in indices_1
# drops all values of pred_and_manual_df that aren't in indices_2

feats_df_new = feats_df_new.iloc[indices_1]
pred_and_manual_df = pred_and_manual_df.iloc[indices_2]
feats_df_new.reset_index(inplace = True, drop = True)
pred_and_manual_df.reset_index(inplace = True, drop = True)

In [15]:
same = list(np.array(feats_df_new["full_path"]) == np.array(pred_and_manual_df["full_path"]))

print(same.count(True))
print(same.count(False))
print(len(same))

#print(same)

28659
0
28659

In [16]:
feats_df_new["classifier_pred_class"] = pred_and_manual_df["pred_class"]

C:\Users\user.SR7872\AppData\Local\Temp\ipykernel_9236\3775421508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feats_df_new["classifier_pred_class"] = pred_and_manual_df["pred_class"]

In [17]:
#its a feats_df of constrained parameters
feats_df_new.head()

feats_df = feats_df_new

In [18]:
print(feats_df.shape)

(28659, 113)

In [19]:
print(feats_df.columns[13:111])

Index(['num_spots', 'Mean', 'Median', 'Area_mean', 'Area_std', 'X_mean',
       'X_std', 'Y_mean', 'Y_std', 'Perim._mean', 'Perim._std', 'BX_mean',
       'BX_std', 'BY_mean', 'BY_std', 'Width_mean', 'Width_std', 'Height_mean',
       'Height_std', 'Major_mean', 'Major_std', 'Minor_mean', 'Minor_std',
       'Angle_mean', 'Angle_std', 'Circ._mean', 'Circ._std', 'Feret_mean',
       'Feret_std', 'IntDen_mean', 'IntDen_std', '%Area_mean', '%Area_std',
       'RawIntDen_mean', 'RawIntDen_std', 'FeretX_mean', 'FeretX_std',
       'FeretY_mean', 'FeretY_std', 'FeretAngle_mean', 'FeretAngle_std',
       'MinFeret_mean', 'MinFeret_std', 'AR_mean', 'AR_std', 'Round_mean',
       'Round_std', 'Solidity_mean', 'Solidity_std', 'num_spots_inverted',
       'Mean_inverted', 'Median_inverted', 'Area_inverted_mean',
       'Area_inverted_std', 'X_inverted_mean', 'X_inverted_std',
       'Y_inverted_mean', 'Y_inverted_std', 'Perim._inverted_mean',
       'Perim._inverted_std', 'BX_inverted_mean', 'BX_inverted_std',
       'BY_inverted_mean', 'BY_inverted_std', 'Width_inverted_mean',
       'Width_inverted_std', 'Height_inverted_mean', 'Height_inverted_std',
       'Major_inverted_mean', 'Major_inverted_std', 'Minor_inverted_mean',
       'Minor_inverted_std', 'Angle_inverted_mean', 'Angle_inverted_std',
       'Circ._inverted_mean', 'Circ._inverted_std', 'Feret_inverted_mean',
       'Feret_inverted_std', 'IntDen_inverted_mean', 'IntDen_inverted_std',
       '%Area_inverted_mean', '%Area_inverted_std', 'RawIntDen_inverted_mean',
       'RawIntDen_inverted_std', 'FeretX_inverted_mean', 'FeretX_inverted_std',
       'FeretY_inverted_mean', 'FeretY_inverted_std',
       'FeretAngle_inverted_mean', 'FeretAngle_inverted_std',
       'MinFeret_inverted_mean', 'MinFeret_inverted_std', 'AR_inverted_mean',
       'AR_inverted_std', 'Round_inverted_mean', 'Round_inverted_std',
       'Solidity_inverted_mean', 'Solidity_inverted_std'],
      dtype='object')

XGBOOST

In [20]:
#! pip install xgboost
#! pip install openpyxl
#! pip install tensorflow
#! pip install graphviz
#! pip install hyperopt

from sklearn.multioutput import MultiOutputRegressor
from sklearn.svm import SVR
import numpy as np
from sklearn.model_selection import RepeatedKFold
from numpy import absolute
from pandas import read_csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from xgboost import XGBRegressor
import openpyxl
from xgboost import cv
from PIL import Image
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import operator
# for loading/processing the images
import tensorflow
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from keras.applications.vgg16 import preprocess_input

# models
from keras.applications.vgg16 import VGG16
from keras.models import Model

# clustering and dimension reduction
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import pickle
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree
import graphviz
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from hyperopt import fmin, tpe, hp,STATUS_OK
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

print("All dependencies present")

C:\Users\user.SR7872\AppData\Local\Programs\Python\Python312\Lib\site-packages\hyperopt\atpe.py:19: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

All dependencies present

In [21]:
np.unique(feats_df["num_spots"].astype(float))

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 150., 151., 152., 153.,
       154., 155., 156., 157., 158., 159., 160., 161., 162., 163., 164.,
       165., 166., 167., 168., 169., 170., 171., 172., 173., 174., 175.,
       176., 177., 178., 179., 180., 181., 182., 183., 184., 185., 186.,
       187., 188., 189., 190., 191., 192., 193., 194., 195., 196., 197.,
       198., 199., 200., 201., 202., 203., 204., 205., 206., 207., 208.,
       209., 210., 211., 212., 213., 214., 215., 216., 217., 218., 219.,
       220., 221., 222., 223., 224., 225., 226., 227., 228., 229., 230.,
       231., 232., 233., 234., 235., 236., 237., 238., 239., 240., 241.,
       242., 243., 244., 245., 246., 247., 248., 249., 250., 251., 252.,
       253., 254., 255., 256., 257., 258., 259., 260., 261., 262., 263.,
       264., 265., 266., 267., 268., 269., 270., 271., 272., 274., 275.,
       276., 277., 278., 279., 280., 281., 283., 284., 285., 286., 288.,
       289., 291., 292., 295., 296., 297., 300., 302., 303., 304., 306.,
       307., 308., 309., 310., 311., 312., 313., 314., 315., 317., 318.,
       319., 321., 322., 323., 324., 328., 331., 332., 333., 334., 335.,
       336., 339., 343., 348., 350., 351., 355., 356., 358., 362., 367.,
       370., 371., 385.])

In [22]:
# scale data 
# uses Standard Scaler, range [-1, 1]

## X (independent variable) --> the feature values themselves
X = feats_df[feats_df.columns[13:111]].astype(float)

## Y (dependent variables) --> the parameter values of Negan and RTO themselves
y = feats_df[["Ua","Ui","Ga","Gi","Da","Di","Ba"]].astype(float)

#Scale data with standardscaler
scaling = StandardScaler()

# Use fit and transform method
scaling.fit(X)
X_scaled = scaling.transform(X)

# select 20 percent for testing
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42) #create training split



# df_train = feats_df.sample(frac = 0.80, random_state = 42)
# df_train.reset_index(inplace = True, drop = True)
# df_val_test = feats_df.drop(df_train.index)

# p_out = 1

# df_val_test = df_val_test.sample(frac = p_out, random_state = 42)
# df_val = df_val_test.sample(frac = 0.5, random_state = 42)
# df_test = df_val_test.drop(df_val.index)

# df_val.reset_index(inplace = True, drop = True)
# df_test.reset_index(inplace = True, drop = True)

In [23]:
print(X_test)
#print(y_train)

[[-0.64846417 -0.95141314 -0.78175594 ... -0.27656263  0.56365538
  -0.24122377]
 [ 0.30827125  0.39681846  1.27917161 ... -0.27656263 -4.37520359
  -0.24122377]
 [-0.63277998  1.33653853  1.27917161 ... -0.27656263  0.56365538
  -0.24122377]
 ...
 [-0.64846417 -0.95141314 -0.78175594 ... -0.27656263  0.56365538
  -0.24122377]
 [ 2.58247841 -0.5522239  -0.78175594 ... -0.27656263 -0.8978437
  -0.24122377]
 [ 0.872902   -0.82186124 -0.78175594 ... -0.27656263  0.08488844
  -0.24122377]]

In [24]:
y_test

             Ua        Ui        Ga        Gi        Da        Di        Ba
20241  0.036670  0.073226  0.040154  0.061430  0.009830  0.850876 -0.101614
14778  0.010814  0.077545  0.084799  0.106047  0.011972  0.344742 -0.120386
25231  0.031524  0.146835  0.162371  0.089494  0.009966  0.948477 -0.151192
26948  0.032629  0.072921  0.088104  0.153645  0.009018  0.894565 -0.164564
12272  0.011581  0.058755  0.142204  0.123917  0.011563  1.160790 -0.115591
...         ...       ...       ...       ...       ...       ...       ...
13827  0.008961  0.052993  0.128148  0.147533  0.010953  0.754449 -0.150162
2855   0.019784  0.072723  0.137530  0.070223  0.011001  0.669717 -0.102735
16710  0.019573  0.059808  0.089377  0.160549  0.010973  0.480674 -0.144362
25107  0.038058  0.123075  0.108594  0.162017  0.008668  0.761952 -0.113683
376    0.026498  0.063018  0.084241  0.095861  0.009453  0.862788 -0.137198

[5732 rows x 7 columns]

In [37]:
model = xgb.XGBRegressor(n_estimators=1000, max_depth=10, eta=0.1, subsample=0.7, colsample_bytree=0.8, num_boost_round=50, objective= "reg:squarederror", device = "cuda")
model.fit(X_train, y_train)

C:\Users\user.SR7872\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [14:18:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\context.cc:49: No visible GPU is found, setting device to CPU.
  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\user.SR7872\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [14:18:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
C:\Users\user.SR7872\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [14:18:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738:
Parameters: { "num_boost_round" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eta=0.1, eval_metric=None,
             feature_types=None, feature_weights=None, gamma=None,
             grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=None, ...)

In [25]:
loaded_model = xgb.XGBRegressor()

loaded_model.load_model('./content/Models/XGB_model.model')

#loaded_model.fit(X_train, y_train)

# make predictions
y_pred = loaded_model.predict(X_test)

pd.DataFrame(data=y_pred) 

# Columns - parameters 1-7
# Rows - Subsample of rows

             0         1         2         3         4         5         6
0     0.033395  0.087170  0.064362  0.110597  0.010077  0.807379 -0.129942
1     0.011164  0.086442  0.089399  0.117670  0.010302  0.697959 -0.130809
2     0.024965  0.140235  0.125021  0.088071  0.010001  0.869328 -0.101000
3     0.035866  0.078264  0.087985  0.120647  0.009795  0.673017 -0.159450
4     0.024965  0.140235  0.125021  0.088071  0.010001  0.869328 -0.101000
...        ...       ...       ...       ...       ...       ...       ...
5727  0.011736  0.069977  0.117183  0.112757  0.009499  1.038847 -0.129972
5728  0.024965  0.140235  0.125021  0.088071  0.010001  0.869328 -0.101000
5729  0.033395  0.087170  0.064362  0.110597  0.010077  0.807379 -0.129942
5730  0.038365  0.133653  0.101905  0.119501  0.009474  0.620962 -0.141445
5731  0.027125  0.062712  0.083409  0.096253  0.009224  0.862280 -0.135911

[5732 rows x 7 columns]

In [41]:
## Save XGBoost Model to File

path = "./content/Models/XGB_model.model"

model.save_model(path)

C:\Users\user.SR7872\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [14:36:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)

In [27]:
# GOAL: To determine the error rate in predicting the value of continuous, parameter data

# Converts test Y values to numpy array
true_vals = np.array(y_test)

# Outputs amount of true values
print(true_vals.shape)

# Outputs amount of predicted values
print(y_pred.shape)

# Sets counters for correct, incorrect, errors numpy array
correct = 0
incorrect = 0
p_errs = np.zeros(7)

# loops through each row in the true_vals array
for i in range(true_vals.shape[0]):
  # predicted value = predicted value from loop
  pred = y_pred[i]
  # true value = true value from loop
  true_val = true_vals[i]
  # Adds to error: absolute percent difference between true and predicted values
  p_errs += (np.abs((pred-true_val)/true_val))

# Outputs error percentages
print((p_errs/true_vals.shape[0])*100)

(5732, 7)
(5732, 7)
[32.13409601 54.19867644 25.56774297 40.13796377  8.68439102 37.65799152
 33.26148726]

In [28]:
# make a dataframe with the names and feat_dfs and inverse_feat_dfs:
real_imj_df = {"path":[],"feats_df":[],"inverse_feats_df":[]}

reg_paths = os.listdir("./content/ImageJ_data/Inverse_resized/")

for path in reg_paths:
  if path != ".ipynb_checkpoints":
    real_imj_df["path"].append(path)
    real_imj_df["feats_df"].append(pd.read_csv("./content/ImageJ_data/Regular_resized/" + path))
    real_imj_df["inverse_feats_df"].append(pd.read_csv("./content/ImageJ_data/Inverse_resized/" + path))

real_df = pd.DataFrame(real_imj_df)

In [45]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None) 
real_df.shape

columns0 = ['feats_df', 'inverse_feats_df']

real_df2 = real_df.drop(columns=columns0)

real_df2

#real_df.head(14)

,path,num_spots,Mean,Median,Area_mean,Area_std,X_mean,X_std,Y_mean,Y_std,Perim._mean,Perim._std,BX_mean,BX_std,BY_mean,BY_std,Width_mean,Width_std,Height_mean,Height_std,Major_mean,Major_std,Minor_mean,Minor_std,Angle_mean,Angle_std,Circ._mean,Circ._std,Feret_mean,Feret_std,IntDen_mean,IntDen_std,%Area_mean,%Area_std,RawIntDen_mean,RawIntDen_std,FeretX_mean,FeretX_std,FeretY_mean,FeretY_std,FeretAngle_mean,FeretAngle_std,MinFeret_mean,MinFeret_std,AR_mean,AR_std,Round_mean,Round_std,Solidity_mean,Solidity_std,num_spots_inverted,Mean_inverted,Median_inverted,Area_inverted_mean,Area_inverted_std,X_inverted_mean,X_inverted_std,Y_inverted_mean,Y_inverted_std,Perim._inverted_mean,Perim._inverted_std,BX_inverted_mean,BX_inverted_std,BY_inverted_mean,BY_inverted_std,Width_inverted_mean,Width_inverted_std,Height_inverted_mean,Height_inverted_std,Major_inverted_mean,Major_inverted_std,Minor_inverted_mean,Minor_inverted_std,Angle_inverted_mean,Angle_inverted_std,Circ._inverted_mean,Circ._inverted_std,Feret_inverted_mean,Feret_inverted_std,IntDen_inverted_mean,IntDen_inverted_std,%Area_inverted_mean,%Area_inverted_std,RawIntDen_inverted_mean,RawIntDen_inverted_std,FeretX_inverted_mean,FeretX_inverted_std,FeretY_inverted_mean,FeretY_inverted_std,FeretAngle_inverted_mean,FeretAngle_inverted_std,MinFeret_inverted_mean,MinFeret_inverted_std,AR_inverted_mean,AR_inverted_std,Round_inverted_mean,Round_inverted_std,Solidity_inverted_mean,Solidity_inverted_std,pred_params
0,bHLH2_OE_(green)_(0-141_thresh.tif.csv,30,67.001,0,350.333333,436.638320,104.649567,63.380542,69.287167,49.347736,105.791967,105.323220,95.300000,64.799254,54.300000,45.721002,18.366667,14.716166,31.333333,28.248107,28.469100,22.259388,11.132167,7.572338,95.829533,41.340200,0.519500,0.271161,34.549767,29.326032,8.933500e+04,1.113428e+05,100.0,0.0,8.933500e+04,1.113428e+05,97.966667,65.061757,61.133333,49.947795,106.094367,30.422104,14.895000,11.599036,2.534433,1.161018,0.472233,0.188002,0.736767,0.158909,3,187.999,255,9830.000000,13840.207585,95.572667,64.063517,36.149333,47.039893,479.711333,643.458785,59.666667,76.054074,0.000000,0.000000,72.333333,90.282273,71.000000,91.224997,70.875333,88.047917,67.994000,87.418781,165.417333,15.370366,0.643667,0.321746,100.305000,128.089096,2.506650e+06,3.529253e+06,100.0,0.0,2.506650e+06,3.529253e+06,59.666667,76.054074,67.000000,94.046088,118.021000,52.215878,71.000000,91.224997,1.264667,0.176532,0.808000,0.123701,0.839333,0.073436,"[0.02614826, 0.062585935, 0.12087097, 0.08383078, 0.010859064, 0.85632795, -0.09742121]"
1,bHLH2_RNAi_(green)_(0-170).tif.csv,0,0.000,0,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,800.000000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.785000,0.000000,282.843000,0.000000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000e+00,100.0,0.0,1.020000e+07,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,"[0.023517208, 0.057141475, 0.07845976, 0.1292734, 0.010278776, 0.76815784, -0.08877929]"
2,F2_260_green)_(0-105).tif.csv,26,70.966,0,428.153846,519.658223,103.716385,53.872307,86.366654,56.292048,99.326923,90.300749,95.576923,54.687344,69.500000,53.847541,17.000000,14.665501,35.038462,27.607804,32.030154,22.516273,11.821077,7.936903,83.427346,31.445279,0.545500,0.229855,37.386077,29.418346,1.091792e+05,1.325128e+05,100.0,0.0,1.091792e+05,1.325128e+05,98.538462,54.670503,87.961538,54.263234,93.984962,27.368451,14.872077,11.791365,2.686885,0.910115,0.428462,0.185528,0.807885,0.137202,1,184.034,255,28868.000000,0.000000,101.886000,0.000000,101.155000,0.000000,1845.727000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,195.203000,0.000000,188.295000,0.000000,60.677000,0.000000,0.106000,0.000000,282.843000,0.000000,7.361340e+06,0.000000e+00,100.0,0.0,7.361340e+06,0.000000e+00,0.000000,0.000000,200.000000,0.000000,45.000000,0.000000,200.000000,0.000000,1.037000,0.000000,0.965000,0.000000,0.723000,0.000000,"[0.023318738, 0.060084313, 0.12086973, 0.11648673, 0.00954962, 0.70141786, -0.0975161]"
3,F2_A 8_(green)_(0-100).tif.csv,9,92.578,0,1613.555556,771.210752,114.434444,60.967917,98.298000,56.395622,235.716333,119.683538,93.333333,65.540488,62.000000,57.263523,43.000000,19.275776,78.555556,47.211371,81.267444,47.188854,24.941556,8.592435,80.759444,34.770839,0.419333,0.157302,87.077667,46.327773,4.114567e+05,1.966587e+05,100.0,0.0,4.114567e+05,1.966587e+05,98.222222,67.698314,88.777778,79.286790,88.086333,29.493138,32.186333,11.473686,3.590667,2.847227,0.372111,0.136953,0.766111,0.104342,4,162.422,255,6369.500000,11016.133407,113.921750,36.502635,37.842750,38.755926,479.377250,810.326836,86.500000,61.210702,11.250000,11.903256,53.500000,84.600532,52.000000,85.460517,49.878750,77.320383,45.701250,75.428649,40.201750,63.391093,0.592500,0.326511,71.400250,114.144371,1.624222e+06,2.809114e+06,100.0,0.0,1.624222e+06,2.809114e+06,86.500000,61.210702,61.250000,80.726003,122.534750,48.099984,51.817750,85.561271,2.398750,1.626927,0.638000,0.348958,0.849000,0.154614,"[0.029240893, 0.06581408, 0.1192591, 0.10536818, 0.00979359, 0.6629838, -0.060676206]"
4,LF10_11-20-23_(green)_(0-152).tif.csv,101,5.699,0,8.851485,11.066304,125.673327,57.972907,88.902515,52.059334,10.451525,8.653331,123.960396,57.832452,87.297030,52.027705,3.435644,2.619107,3.188119,2.423944,3.860287,2.502460,2.196881,1.250776,50.320287,53.900986,0.857059,0.194583,4.505861,3.106018,2.257129e+03,2.821908e+03,100.0,0.0,2.257129e+03,2.821908e+03,124.089109,57.843781,88.920792,51.956509,103.979446,47.466852,2.599564,1.875266,1.738505,0.579683,0.643267,0.218933,0.857396,0.144207,2,249.301,255,19553.000000,19551.000000,149.373000,50.127000,81.072500,19.072500,405.556000,400.728000,99.500000,99.500000,30.500000,30.500000,100.500000,99.500000,101.000000,99.000000,113.250500,110.993500,111.578500,110.450500,105.140500,15.140500,0.878000,0.122000,142.539500,140.303500,4.986015e+06,4.985505e+06,100.0,0.0,4.986015e+06,4.985505e+06,99.500000,99.500000,30.500000,30.500000,125.782500,9.217500,100.500000,99.500000,1.505000,0.495000,0.745000,0.245000,0.989000,0.011000,"[0.022122597, 0.10830527, 0.12630259, 0.11860634, 0.0105213, 0.6667085, -0.10096822]"
5,MLC_F1_11-20-23_(green)_(0-105).tif.csv,77,15.306,0,31.181818,46.025890,101.898026,40.868593,104.009818,57.481703,19.575195,18.250837,99.701299,41.001763,100.246753,57.180315,4.337662,3.451370,7.363636,7.059872,7.314792,6.449969,3.544974,2.646633,75.761312,40.966277,0.796364,0.213884,8.155052,7.126948,7.951364e+03,1.173660e+04,100.0,0.0,7.951364e+03,1.173660e+04,100.389610,40.993239,103.298701,57.855410,100.865364,32.826527,4.046351,3.194558,2.004753,0.920000,0.585714,0.222167,0.852494,0.123426,1,239.694,255,37599.000000,0.000000,99.823000,0.000000,99.313000,0.000000,808.042000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,219.495000,0.000000,218.104000,0.000000,13.637000,0.000000,0.724000,0.000000,282.843000,0.000000,9.587745e+06,0.000000e+00,100.0,0.0,9.587745e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.006000,0.000000,0.994000,0.000000,0.940000,0.000000,"[0.021287328, 0.123894654, 0.09693768, 0.12160463, 0.010399619, 0.81738204, -0.096936755]"
6,mpar_rto(c-c)_(green)_(0-137).tif.csv,49,23.479,0,75.163265,103.827240,99.147755,55.940428,74.931612,51.325268,36.572388,37.781366,95.387755,55.720445,68.224490,47.695576,7.571429,6.676184,13.428571,13.490738,12.331796,11.379018,5.113531,3.973676,73.345184,38.726102,0.654939,0.264055,14.381224,13.651513,1.916663e+04,2.647595e+04,100.0,0.0,1.916663e+04,2.647595e+04,96.469388,56.061956,74.387755,52.484329,98.199592,32.841924,6.559959,5.483810,2.445878,1.308504,0.527082,0.253666,0.789898,0.171918,1,231.521,255,36317.000000,0.000000,99.125000,0.000000,98.020000,0.000000,810.728000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,216.098000,0.000000,213.978000,0.000000,6.379000,0.000000,0.694000,0.000000,282.843000,0.000000,9.260835e+06,0.000000e+00,100.0,0.0,9.260835e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.010000,0.000000,0.990000,0.000000,0.908000,0.000000,"[0.02338564, 0.11086314, 0.10433803, 0.11101844, 0.010527888, 0.75643164, -0.08920884]"
7,mpar_rto_crispr_(green)_(0-155).tif.csv,2,251.322,255,19711.500000,19688.500000,148.632000,49.216000,51.684500,49.271500,437.255000,417.941000,97.000000,97.000000,0.000000,0.000000,103.000000,97.000000,103.000000,97.000000,115.674500,108.751500,113.879500,109.649500,124.750000,2.012000,0.726000,0.049000,145.664000,137.179000,5.026432e+06,5.020568e+06,100.0,0.0,5.026432e+06,5.020568e+06,97.000000,97.000000,0.000000,0.000000,135.000000,0.000000,102.700000,97.300000,1.320500,0.316500,0.803500,0.192500,0.927500,0.059500,6,3.678,0,96.166667,90.780719,116.399833,76.090823,63.316667,68.682097,39.361167,32.887105,112.666667,75.770853,55.833333,68.594015,7.666667,6.342099,15.166667,14.667614,14.718667,13.570203,6.486500,4.905350,58.449500,33.195085,0.754000,0.263463,16.280500,14.403171,2.452250e+04,2.314908e+04,100.0,0.0,2.452250e+04,2.314908e+04,114.500000,75.583839,70.000000,68.471405,85.368333,34.511534,7.389667,6.291349,2.470333,2.450747,0.641333,0.259052,0.912833,0.070862,"[0.019596737, 0.11570201, 0.120735265, 0.10527825, 0.009731314, 0.9733093, -0.082604244]"
8,mpar_wt_(green)_(0-170).tif.csv,66,8.077,0,19.196970,18.371767,97.896258,52.566051,95.364621,53.682640,15.332273,9.204770,95.500000,52.587085,92.939394,53.159816,4.878788,2.549600,4.939394,3.370454,5.807909,3.168420,3.409803,1.759495,92.356000,57.595572,0.861833,0.154268,6.494227,3.458627,4.895227e+03,4.684800e+03,100.0,0.0,4.895227e+03,4.684800e+03,95.833333,52.615697,95.484848,54.545572,111.274424,46.307654,3.805500,1.983291,1.763136,0.530357,0.614000,0.165891,0.844894,0.093472,1,246.923,255,38733.000000,0.000000,100.011000,0.000000,99.631000,0.000000,843.012000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,222.529000,0.000000,221.618000,0.000000,5.282000,0.000000,0.685000,0.000000,282.843000,0.000000,9.876915e+06,0.000000e+00,100.0,0.0,9.876915e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.004000,0.000000,0.996000,0.000000,0.968000,0.000000,"[0.02325455, 0.112960175, 0.096100986, 0.09682001, 0.010569133, 0.7510395, -0.08745719]"
9,NEGAN_crispr_(green)_(0-150).tif.csv,0,0.000,0,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,800.000000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.785000,0.000000,282.843000,0.000000,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1,255.000,255,40000.000000,0.000000,100.000000,0.000000,100.000000,0.000000,797.657000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,225.676000,0.000000,225.676000,0.000000,0.000000,0.000000,0.790000,0.000000,282.843000,0.000000,1.020000e+07,0.000000e+00,100.0,0.0,1.020000e+07,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,"[0.023517208, 0.057141475, 0.07845976, 0.1292734, 0.010278776, 0.76815784, -0.08877929]"
10,RTO_rnai_high_(green)_(0-103).tif.csv,11,128.246,255,1828.818182,5677.547083,113.048091,65.100510,40.077091,42.948935,195.803364,544.507525,101.090909,73.301934,28.545455,39.326983,23.636364,53.290410,22.545455,56.343691,21.421909,46.851991,16.473273,42.294751,23.064273,37.259117,0.671182,0.350863,30.750000,72.401649,4.663486e+05,1.447775e+06,100.0,0.0,4.663486e+05,1.447775e+06,101.454545,73.523483,31.000000,38.083640,121.365909,41.616273,20.817909,53.213065,1.915636,1.217189,0.704182,0.314290,0.854727,0.196756,48,126.754,0,414.229167,1530.426768,100.006062,44.350497,69.618417,54.639683,71.881896,211.143185,94.250000,44.247175,61.000000,56.220177,10.562500,22.046264,16.791667,42.311325,15.150167,32.905507,7.268125,13.323091,66.951479,58.625727,0.826000,0.264367,19.489729,46.431683,1.056284e+05,3.902588e+05,100.0,0.0,1.056284e+05,3.902588e+05,95.333333,44.349621,68.645833,58.593405,117.005208,35.754028,9.485479,20.990371,1.680583,1.042379,0.696771,0.219777,0.882354,0.131232,"[0.022579767, 0.12983255, 0.14447114, 0.11790998, 0.0095764715, 0.7869343, -0.105486326]"
11,RTO_rnai_low_(green)_(0-115).tif.csv,91,13.528,0,23.318681,39.296808,107.970220,46.996468,83.078824,52.120805,18.276022,18.081455,105.923077,47.434913,79.659341,50.818838,4.076923,3.604731,6.835165,6.696339,6.655802,5.625546,3.008747,2.487333,72.963319,41.886223,0.743527,0.243147,7.635242,6.819511,5.946264e+03,1.002069e+04,100.0,0.0,5.946264e+03,1.002069e+04,106.329670,47.511492,82.648352,52.371952,99.644407,34.345456,3.593000,3.210409,2.311527,1.326418,0.542692,0.229538,0.818934,0.136272,1,241.472,255,37878.000000,0.000000,100.297000,0.000000,98.801000,0.000000,825.213000,0.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,0.000000,220.784000,0.000000,218.439000,0.000000,175.665000,0.000000,0.699000,0.000000,282.843000,0.000000,9.658890e+06,0.000000e+00,100.0,0.0,9.658890e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,135.000000,0.000000,200.000000,0.000000,1.011000,0.000000,0.989000,0.000000,0.947000,0.000000,"[0.027059758, 0.11459971, 0.100065485, 0.10730852, 0.010288622, 0.6369645, -0.088772774]"
12,RTO_rnai_med_(green)_(0-109).tif.csv,32,62.124,0,304.531250,876.516507,104.642344,49.916328,82.908906,45.964830,98.939469,229.053596,97.843750,52.672994,69.250000,46.896828,13.187500,23.177896,23.937500,43.999956,18.785969,27.853125,7.510688,11.242490,71.322094,47.638579,0.599312,0.316321,25.907531,45.346692,7.765547e+04,2.235117e+05,100.0,0.0,7.765547e+04,2.235117e+05,99.156250,52.276375,81.218750,50.956314,105.170656,32.194007,11.135063,19.819332,2.472656,1.591892,0.570969,0.297737,0.764094,0.196071,7,192.876,255,4322.142857,10305.987156,84.919429,42.163829,101.338143,58.868357,420.444429,961.335095,67.000000,48.296702,84.285714,64.853052,36.285714,67.748936,35.000000,67.966378,36.615143,68.951076,32.029000,62.839147,56.351429,65.399852,0.745714,0.337601,49.510429,96.095328,1.102146e+06,2.628027e+06,100.0,0.0,1.102146e+06,2.628027e+06,67.714286,48.962710,84.857143,65.627583,136.734000,8.210170,34.848857,68.029623,1.249286,0.436381,0.865714,0.189952,0.895286,0.102845,"[0.018316804, 0.06116261, 0.12642136, 0.07679688, 0.010155454, 0.8142942, -0.1077055]"

In [30]:
# Add regular features

# first list is mean, second list is std except for mean and median
feats = {'Mean':[],'Median':[],'Area':[[],[]], 'X':[[],[]], 'Y':[[],[]], 'Perim.':[[],[]], 'BX':[[],[]],
         'BY':[[],[]], 'Width':[[],[]], 'Height':[[],[]], 'Major':[[],[]], 'Minor':[[],[]],
       'Angle':[[],[]], 'Circ.':[[],[]], 'Feret':[[],[]], 'IntDen':[[],[]], '%Area':[[],[]],
       'RawIntDen':[[],[]], 'FeretX':[[],[]], 'FeretY':[[],[]], 'FeretAngle':[[],[]], 'MinFeret':[[],[]], 'AR':[[],[]],
       'Round':[[],[]], 'Solidity':[[],[]]}

# feats = {'Mean_inverted':[],'Median_inverted':[],'Area':[[],[]], 'X':[[],[]], 'Y':[[],[]], 'Perim.':[[],[]], 'BX':[[],[]],
#          'BY':[[],[]], 'Width':[[],[]], 'Height':[[],[]], 'Major':[[],[]], 'Minor':[[],[]],
#        'Angle':[[],[]], 'Circ.':[[],[]], 'Feret':[[],[]], 'IntDen':[[],[]], '%Area':[[],[]],
#        'RawIntDen':[[],[]], 'FeretX':[[],[]], 'FeretY':[[],[]], 'FeretAngle':[[],[]], 'MinFeret':[[],[]], 'AR':[[],[]],
#        'Round':[[],[]], 'Solidity':[[],[]]}


counter = 0

# iterate through all sims
for n in range(real_df.shape[0]): # grab the feats dataframe for this sim
  fdf = real_df["feats_df"][n] #iterate through all feats within the feats dictionary

  for i in range(len(feats.keys())): # select the current feat
    feat = list(feats.keys())[i]

    # if feat in ['Mean_inverted','Median_inverted']: # check for feats that should be added from the overall measurement (first row)
    if feat in ['Mean','Median']: # check for feats that should be added from the overall measurement (first row)
      # feats[feat].append(fdf[feat[0:-9]][0]) #inverse
      feats[feat].append(fdf[feat[:]][0])
      # feats[feat].append(fdf[feat][0])

    else:
      if fdf.shape[0] <= 1: # check if the fdf is only one measurement (empty result)
        feats[feat][0].append(np.mean(np.array(fdf[feat][0]))) # mean of sole measurement
        feats[feat][1].append(np.std(np.array(fdf[feat][0]))) #std of sole measurement (0)

      else:
        feats[feat][0].append(np.mean(np.array(fdf[feat][1:]))) # add mean for each of the rest of the feats using the remaining rows
        feats[feat][1].append(np.std(np.array(fdf[feat][1:]))) # add std for each of the rest of the feats using the remaining rows

  if counter % 1000 == 0:
    print(counter)
  counter += 1

print("Counting done")

0
Counting done

In [31]:
num_spots = []

for i in range(real_df.shape[0]):
  fdf = real_df["feats_df"][i] #iterate through all feats within the feats dictionary
  if fdf.shape[0] <= 1:
    num_spots.append(0)
  else:
    num_spots.append(fdf.shape[0]-1)

# feats_df["num_spots_inverted"] = num_spots
real_df["num_spots"] = num_spots

In [32]:
for key in list(feats.keys()):
  # if key in ['Mean_inverted','Median_inverted']:
  if key in ['Mean','Median']:
    real_df[key] = feats[key]
  else:
    # feats_df[key + "_inverted_mean"] = feats[key][0]
    # feats_df[key + "_inverted_std"] = feats[key][1]
    real_df[key + "_mean"] = feats[key][0]
    real_df[key + "_std"] = feats[key][1]

In [33]:
# Add regular features

# first list is mean, second list is std except for mean and median
# feats = {'Mean':[],'Median':[],'Area':[[],[]], 'X':[[],[]], 'Y':[[],[]], 'Perim.':[[],[]], 'BX':[[],[]],
#          'BY':[[],[]], 'Width':[[],[]], 'Height':[[],[]], 'Major':[[],[]], 'Minor':[[],[]],
#        'Angle':[[],[]], 'Circ.':[[],[]], 'Feret':[[],[]], 'IntDen':[[],[]], '%Area':[[],[]],
#        'RawIntDen':[[],[]], 'FeretX':[[],[]], 'FeretY':[[],[]], 'FeretAngle':[[],[]], 'MinFeret':[[],[]], 'AR':[[],[]],
#        'Round':[[],[]], 'Solidity':[[],[]]}

feats = {'Mean_inverted':[],'Median_inverted':[],'Area':[[],[]], 'X':[[],[]], 'Y':[[],[]], 'Perim.':[[],[]], 'BX':[[],[]],
         'BY':[[],[]], 'Width':[[],[]], 'Height':[[],[]], 'Major':[[],[]], 'Minor':[[],[]],
       'Angle':[[],[]], 'Circ.':[[],[]], 'Feret':[[],[]], 'IntDen':[[],[]], '%Area':[[],[]],
       'RawIntDen':[[],[]], 'FeretX':[[],[]], 'FeretY':[[],[]], 'FeretAngle':[[],[]], 'MinFeret':[[],[]], 'AR':[[],[]],
       'Round':[[],[]], 'Solidity':[[],[]]}


counter = 0

# iterate through all sims
for n in range(real_df.shape[0]): # grab the feats dataframe for this sim
  fdf = real_df["inverse_feats_df"][n] #iterate through all feats within the feats dictionary

  for i in range(len(feats.keys())): # select the current feat
    feat = list(feats.keys())[i]

    if feat in ['Mean_inverted','Median_inverted']: # check for feats that should be added from the overall measurement (first row)
    # if feat in ['Mean','Median']: # check for feats that should be added from the overall measurement (first row)
      feats[feat].append(fdf[feat[0:-9]][0]) #inverse
      # feats[feat].append(fdf[feat[:]][0])

    else:
      if fdf.shape[0] <= 1: # check if the fdf is only one measurement (empty result)
        feats[feat][0].append(np.mean(np.array(fdf[feat][0]))) # mean of sole measurement
        feats[feat][1].append(np.std(np.array(fdf[feat][0]))) #std of sole measurement (0)

      else:
        feats[feat][0].append(np.mean(np.array(fdf[feat][1:]))) # add mean for each of the rest of the feats using the remaining rows
        feats[feat][1].append(np.std(np.array(fdf[feat][1:]))) # add std for each of the rest of the feats using the remaining rows

  if counter % 1000 == 0:
    print(counter)
  counter += 1

print("Counter complete")

0
Counter complete

In [34]:
num_spots = []

for i in range(real_df.shape[0]):
  fdf = real_df["inverse_feats_df"][i] #iterate through all feats within the feats dictionary
  if fdf.shape[0] <= 1:
    num_spots.append(0)
  else:
    num_spots.append(fdf.shape[0]-1)

real_df["num_spots_inverted"] = num_spots
# real_df["num_spots"] = num_spots

In [35]:
for key in list(feats.keys()):
  if key in ['Mean_inverted','Median_inverted']:
  # if key in ['Mean','Median']:
    real_df[key] = feats[key]
  else:
    real_df[key + "_inverted_mean"] = feats[key][0]
    real_df[key + "_inverted_std"] = feats[key][1]
    # real_df[key + "_mean"] = feats[key][0]
    # real_df[key + "_std"] = feats[key][1]

In [36]:
print(real_df.columns[3:101])

Index(['num_spots', 'Mean', 'Median', 'Area_mean', 'Area_std', 'X_mean', 'X_std', 'Y_mean', 'Y_std', 'Perim._mean', 'Perim._std', 'BX_mean', 'BX_std', 'BY_mean', 'BY_std', 'Width_mean', 'Width_std', 'Height_mean', 'Height_std', 'Major_mean', 'Major_std', 'Minor_mean', 'Minor_std', 'Angle_mean', 'Angle_std', 'Circ._mean', 'Circ._std', 'Feret_mean', 'Feret_std', 'IntDen_mean', 'IntDen_std', '%Area_mean', '%Area_std', 'RawIntDen_mean', 'RawIntDen_std', 'FeretX_mean', 'FeretX_std', 'FeretY_mean', 'FeretY_std', 'FeretAngle_mean', 'FeretAngle_std', 'MinFeret_mean', 'MinFeret_std', 'AR_mean', 'AR_std', 'Round_mean', 'Round_std', 'Solidity_mean', 'Solidity_std', 'num_spots_inverted', 'Mean_inverted', 'Median_inverted', 'Area_inverted_mean', 'Area_inverted_std', 'X_inverted_mean', 'X_inverted_std', 'Y_inverted_mean', 'Y_inverted_std', 'Perim._inverted_mean', 'Perim._inverted_std', 'BX_inverted_mean', 'BX_inverted_std', 'BY_inverted_mean', 'BY_inverted_std', 'Width_inverted_mean',
       'Width_inverted_std', 'Height_inverted_mean', 'Height_inverted_std', 'Major_inverted_mean', 'Major_inverted_std', 'Minor_inverted_mean', 'Minor_inverted_std', 'Angle_inverted_mean', 'Angle_inverted_std', 'Circ._inverted_mean', 'Circ._inverted_std', 'Feret_inverted_mean', 'Feret_inverted_std', 'IntDen_inverted_mean', 'IntDen_inverted_std', '%Area_inverted_mean', '%Area_inverted_std', 'RawIntDen_inverted_mean', 'RawIntDen_inverted_std', 'FeretX_inverted_mean', 'FeretX_inverted_std', 'FeretY_inverted_mean', 'FeretY_inverted_std', 'FeretAngle_inverted_mean', 'FeretAngle_inverted_std', 'MinFeret_inverted_mean', 'MinFeret_inverted_std', 'AR_inverted_mean', 'AR_inverted_std', 'Round_inverted_mean', 'Round_inverted_std', 'Solidity_inverted_mean', 'Solidity_inverted_std'],
      dtype='object')

In [ ]:
real_df.head()

In [38]:
# select features of real images
real_feats = real_df[real_df.columns[3:101]]

#scale data
scaling=StandardScaler()

# Use fit and transform method
scaling.fit(real_feats)
real_feats_scaled = scaling.transform(real_feats)



# predict params of images from real feats
y_pred = loaded_model.predict(real_feats_scaled)

real_df["pred_params"] = list(y_pred)

In [39]:
real_df["pred_params"][0]

array([ 0.02614826,  0.06258593,  0.12087097,  0.08383078,  0.01085906,
        0.85632795, -0.09742121], dtype=float32)

In [40]:
real_df["pred_params"][0]

array([ 0.02614826,  0.06258593,  0.12087097,  0.08383078,  0.01085906,
        0.85632795, -0.09742121], dtype=float32)

In [41]:
## TODO: Grab dataframe at the top (w/ all the features), drop all unnessesary columns (diff. from real_df, drop parameters)
## choose first five images and run it and see how close they are. 

for i in range(real_df.shape[0]):
  print(real_df["path"][i])
  print(real_df["pred_params"][i])

bHLH2_OE_(green)_(0-141_thresh.tif.csv
[ 0.02614826  0.06258593  0.12087097  0.08383078  0.01085906  0.85632795
 -0.09742121]
bHLH2_RNAi_(green)_(0-170).tif.csv
[ 0.02351721  0.05714148  0.07845976  0.1292734   0.01027878  0.76815784
 -0.08877929]
F2_260_green)_(0-105).tif.csv
[ 0.02331874  0.06008431  0.12086973  0.11648673  0.00954962  0.70141786
 -0.0975161 ]
F2_A 8_(green)_(0-100).tif.csv
[ 0.02924089  0.06581408  0.1192591   0.10536818  0.00979359  0.6629838
 -0.06067621]
LF10_11-20-23_(green)_(0-152).tif.csv
[ 0.0221226   0.10830527  0.12630259  0.11860634  0.0105213   0.6667085
 -0.10096822]
MLC_F1_11-20-23_(green)_(0-105).tif.csv
[ 0.02128733  0.12389465  0.09693768  0.12160463  0.01039962  0.81738204
 -0.09693675]
mpar_rto(c-c)_(green)_(0-137).tif.csv
[ 0.02338564  0.11086314  0.10433803  0.11101844  0.01052789  0.75643164
 -0.08920884]
mpar_rto_crispr_(green)_(0-155).tif.csv
[ 0.01959674  0.11570201  0.12073527  0.10527825  0.00973131  0.9733093
 -0.08260424]
mpar_wt_(green)_(0-170).tif.csv
[ 0.02325455  0.11296017  0.09610099  0.09682001  0.01056913  0.7510395
 -0.08745719]
NEGAN_crispr_(green)_(0-150).tif.csv
[ 0.02351721  0.05714148  0.07845976  0.1292734   0.01027878  0.76815784
 -0.08877929]
RTO_rnai_high_(green)_(0-103).tif.csv
[ 0.02257977  0.12983255  0.14447114  0.11790998  0.00957647  0.7869343
 -0.10548633]
RTO_rnai_low_(green)_(0-115).tif.csv
[ 0.02705976  0.11459971  0.10006548  0.10730852  0.01028862  0.6369645
 -0.08877277]
RTO_rnai_med_(green)_(0-109).tif.csv
[ 0.0183168   0.06116261  0.12642136  0.07679688  0.01015545  0.8142942
 -0.1077055 ]